// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const bumpRunStep = `-- name: BumpRunStep :exec
UPDATE agent_runs SET step_count = step_count + 1, cost_usd = cost_usd + $2 WHERE id = $1
`

type BumpRunStepParams struct {
	ID      uuid.UUID `json:"id"`
	CostUsd float64   `json:"cost_usd"`
}

func (q *Queries) BumpRunStep(ctx context.Context, arg BumpRunStepParams) error {
	_, err := q.db.Exec(ctx, bumpRunStep, arg.ID, arg.CostUsd)
	return err
}

const cancelRun = `-- name: CancelRun :exec
UPDATE agent_runs SET status = 'cancelled', ended_at = now() WHERE id = $1 AND status NOT IN ('done','failed','cancelled')
`

func (q *Queries) CancelRun(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelRun, id)
	return err
}

const claimRun = `-- name: ClaimRun :one
UPDATE agent_runs SET status = 'running', owner_pid = $2, heartbeat_at = now(), started_at = COALESCE(started_at, now())
WHERE id = $1 AND (status IN ('queued','paused_steer') OR (status = 'running' AND heartbeat_at < now() - interval '90 seconds'))
RETURNING id, agent_id, conversation_id, user_id, trigger_id, status, request, tool_policies, max_steps, step_count, first_message_id, cost_usd, error, heartbeat_at, owner_pid, started_at, ended_at, created_at, updated_at
`

type ClaimRunParams struct {
	ID       uuid.UUID `json:"id"`
	OwnerPid *string   `json:"owner_pid"`
}

// Atomically take a queued/paused/stale-running run for this process.
func (q *Queries) ClaimRun(ctx context.Context, arg ClaimRunParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, claimRun, arg.ID, arg.OwnerPid)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ConversationID,
		&i.UserID,
		&i.TriggerID,
		&i.Status,
		&i.Request,
		&i.ToolPolicies,
		&i.MaxSteps,
		&i.StepCount,
		&i.FirstMessageID,
		&i.CostUsd,
		&i.Error,
		&i.HeartbeatAt,
		&i.OwnerPid,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countOpenRunsForAgent = `-- name: CountOpenRunsForAgent :one
SELECT count(*) FROM agent_runs WHERE agent_id = $1 AND status IN ('queued','running','paused_approval','paused_steer','paused_manual')
`

func (q *Queries) CountOpenRunsForAgent(ctx context.Context, agentID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenRunsForAgent, agentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (owner_id, project_id, name, goal, system_prompt, model_policy, tool_allowlist, tool_policies, max_steps)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, owner_id, name, goal, system_prompt, model_policy, tool_allowlist, tool_policies, mcp_servers, memory_config, max_steps, enabled, created_at, updated_at, project_id, last_run_at
`

type CreateAgentParams struct {
	OwnerID       uuid.UUID       `json:"owner_id"`
	ProjectID     uuid.NullUUID   `json:"project_id"`
	Name          string          `json:"name"`
	Goal          string          `json:"goal"`
	SystemPrompt  string          `json:"system_prompt"`
	ModelPolicy   json.RawMessage `json:"model_policy"`
	ToolAllowlist []string        `json:"tool_allowlist"`
	ToolPolicies  json.RawMessage `json:"tool_policies"`
	MaxSteps      int32           `json:"max_steps"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.OwnerID,
		arg.ProjectID,
		arg.Name,
		arg.Goal,
		arg.SystemPrompt,
		arg.ModelPolicy,
		arg.ToolAllowlist,
		arg.ToolPolicies,
		arg.MaxSteps,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Goal,
		&i.SystemPrompt,
		&i.ModelPolicy,
		&i.ToolAllowlist,
		&i.ToolPolicies,
		&i.McpServers,
		&i.MemoryConfig,
		&i.MaxSteps,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.LastRunAt,
	)
	return i, err
}

const createApproval = `-- name: CreateApproval :one
INSERT INTO approvals (run_id, step_seq, tool_call_id, tool_name, args) VALUES ($1, $2, $3, $4, $5) RETURNING id, run_id, step_seq, tool_call_id, tool_name, args, status, decided_by, decided_at, note, created_at
`

type CreateApprovalParams struct {
	RunID      uuid.UUID       `json:"run_id"`
	StepSeq    int32           `json:"step_seq"`
	ToolCallID string          `json:"tool_call_id"`
	ToolName   string          `json:"tool_name"`
	Args       json.RawMessage `json:"args"`
}

func (q *Queries) CreateApproval(ctx context.Context, arg CreateApprovalParams) (Approval, error) {
	row := q.db.QueryRow(ctx, createApproval,
		arg.RunID,
		arg.StepSeq,
		arg.ToolCallID,
		arg.ToolName,
		arg.Args,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepSeq,
		&i.ToolCallID,
		&i.ToolName,
		&i.Args,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO agent_runs (agent_id, conversation_id, user_id, trigger_id, status, request, tool_policies, max_steps, first_message_id, owner_pid, started_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, CASE WHEN $5 = 'running' THEN now() ELSE NULL END)
RETURNING id, agent_id, conversation_id, user_id, trigger_id, status, request, tool_policies, max_steps, step_count, first_message_id, cost_usd, error, heartbeat_at, owner_pid, started_at, ended_at, created_at, updated_at
`

type CreateRunParams struct {
	AgentID        uuid.NullUUID   `json:"agent_id"`
	ConversationID uuid.UUID       `json:"conversation_id"`
	UserID         uuid.NullUUID   `json:"user_id"`
	TriggerID      uuid.NullUUID   `json:"trigger_id"`
	Status         string          `json:"status"`
	Request        json.RawMessage `json:"request"`
	ToolPolicies   json.RawMessage `json:"tool_policies"`
	MaxSteps       int32           `json:"max_steps"`
	FirstMessageID uuid.NullUUID   `json:"first_message_id"`
	OwnerPid       *string         `json:"owner_pid"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.AgentID,
		arg.ConversationID,
		arg.UserID,
		arg.TriggerID,
		arg.Status,
		arg.Request,
		arg.ToolPolicies,
		arg.MaxSteps,
		arg.FirstMessageID,
		arg.OwnerPid,
	)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ConversationID,
		&i.UserID,
		&i.TriggerID,
		&i.Status,
		&i.Request,
		&i.ToolPolicies,
		&i.MaxSteps,
		&i.StepCount,
		&i.FirstMessageID,
		&i.CostUsd,
		&i.Error,
		&i.HeartbeatAt,
		&i.OwnerPid,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTrigger = `-- name: CreateTrigger :one
INSERT INTO agent_triggers (agent_id, kind, name, spec, secret_hash, next_run_at)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, agent_id, kind, spec, secret_hash, enabled, created_at, name, next_run_at, last_run_at, last_error
`

type CreateTriggerParams struct {
	AgentID    uuid.UUID       `json:"agent_id"`
	Kind       string          `json:"kind"`
	Name       string          `json:"name"`
	Spec       json.RawMessage `json:"spec"`
	SecretHash []byte          `json:"secret_hash"`
	NextRunAt  *time.Time      `json:"next_run_at"`
}

func (q *Queries) CreateTrigger(ctx context.Context, arg CreateTriggerParams) (AgentTrigger, error) {
	row := q.db.QueryRow(ctx, createTrigger,
		arg.AgentID,
		arg.Kind,
		arg.Name,
		arg.Spec,
		arg.SecretHash,
		arg.NextRunAt,
	)
	var i AgentTrigger
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Kind,
		&i.Spec,
		&i.SecretHash,
		&i.Enabled,
		&i.CreatedAt,
		&i.Name,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastError,
	)
	return i, err
}

const decideApproval = `-- name: DecideApproval :one
UPDATE approvals SET status = $2, decided_by = $3, decided_at = now(), note = $4
WHERE id = $1 AND status = 'pending' RETURNING id, run_id, step_seq, tool_call_id, tool_name, args, status, decided_by, decided_at, note, created_at
`

type DecideApprovalParams struct {
	ID        uuid.UUID     `json:"id"`
	Status    string        `json:"status"`
	DecidedBy uuid.NullUUID `json:"decided_by"`
	Note      *string       `json:"note"`
}

func (q *Queries) DecideApproval(ctx context.Context, arg DecideApprovalParams) (Approval, error) {
	row := q.db.QueryRow(ctx, decideApproval,
		arg.ID,
		arg.Status,
		arg.DecidedBy,
		arg.Note,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepSeq,
		&i.ToolCallID,
		&i.ToolName,
		&i.Args,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const decideApprovalByCall = `-- name: DecideApprovalByCall :one
UPDATE approvals SET status = $3, decided_by = $4, decided_at = now()
WHERE run_id = $1 AND tool_call_id = $2 AND status = 'pending' RETURNING id, run_id, step_seq, tool_call_id, tool_name, args, status, decided_by, decided_at, note, created_at
`

type DecideApprovalByCallParams struct {
	RunID      uuid.UUID     `json:"run_id"`
	ToolCallID string        `json:"tool_call_id"`
	Status     string        `json:"status"`
	DecidedBy  uuid.NullUUID `json:"decided_by"`
}

func (q *Queries) DecideApprovalByCall(ctx context.Context, arg DecideApprovalByCallParams) (Approval, error) {
	row := q.db.QueryRow(ctx, decideApprovalByCall,
		arg.RunID,
		arg.ToolCallID,
		arg.Status,
		arg.DecidedBy,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepSeq,
		&i.ToolCallID,
		&i.ToolName,
		&i.Args,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = $1
`

func (q *Queries) DeleteAgent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgent, id)
	return err
}

const deleteTrigger = `-- name: DeleteTrigger :exec
DELETE FROM agent_triggers WHERE id = $1 AND agent_id = $2
`

type DeleteTriggerParams struct {
	ID      uuid.UUID `json:"id"`
	AgentID uuid.UUID `json:"agent_id"`
}

func (q *Queries) DeleteTrigger(ctx context.Context, arg DeleteTriggerParams) error {
	_, err := q.db.Exec(ctx, deleteTrigger, arg.ID, arg.AgentID)
	return err
}

const findToolStep = `-- name: FindToolStep :one
SELECT id, run_id, seq, kind, input, output, checkpoint, usage, error, started_at, ended_at FROM agent_steps WHERE run_id = $1 AND kind = 'tool' AND input->>'call_id' = $2::text ORDER BY seq DESC LIMIT 1
`

type FindToolStepParams struct {
	RunID  uuid.UUID `json:"run_id"`
	CallID string    `json:"call_id"`
}

func (q *Queries) FindToolStep(ctx context.Context, arg FindToolStepParams) (AgentStep, error) {
	row := q.db.QueryRow(ctx, findToolStep, arg.RunID, arg.CallID)
	var i AgentStep
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Seq,
		&i.Kind,
		&i.Input,
		&i.Output,
		&i.Checkpoint,
		&i.Usage,
		&i.Error,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const finishRun = `-- name: FinishRun :exec
UPDATE agent_runs SET status = 'done', ended_at = now()
WHERE id = $1 AND status NOT IN ('paused_manual','cancelled')
`

// Mark a run done unless the monitor paused or cancelled it meanwhile.
func (q *Queries) FinishRun(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, finishRun, id)
	return err
}

const finishStep = `-- name: FinishStep :exec
UPDATE agent_steps SET output = $2, usage = $3, error = $4, checkpoint = COALESCE($5, checkpoint), ended_at = now() WHERE id = $1
`

type FinishStepParams struct {
	ID         uuid.UUID       `json:"id"`
	Output     json.RawMessage `json:"output"`
	Usage      json.RawMessage `json:"usage"`
	Error      *string         `json:"error"`
	Checkpoint json.RawMessage `json:"checkpoint"`
}

func (q *Queries) FinishStep(ctx context.Context, arg FinishStepParams) error {
	_, err := q.db.Exec(ctx, finishStep,
		arg.ID,
		arg.Output,
		arg.Usage,
		arg.Error,
		arg.Checkpoint,
	)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT id, owner_id, name, goal, system_prompt, model_policy, tool_allowlist, tool_policies, mcp_servers, memory_config, max_steps, enabled, created_at, updated_at, project_id, last_run_at FROM agents WHERE id = $1
`

func (q *Queries) GetAgent(ctx context.Context, id uuid.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Goal,
		&i.SystemPrompt,
		&i.ModelPolicy,
		&i.ToolAllowlist,
		&i.ToolPolicies,
		&i.McpServers,
		&i.MemoryConfig,
		&i.MaxSteps,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.LastRunAt,
	)
	return i, err
}

const getApproval = `-- name: GetApproval :one
SELECT id, run_id, step_seq, tool_call_id, tool_name, args, status, decided_by, decided_at, note, created_at FROM approvals WHERE id = $1
`

func (q *Queries) GetApproval(ctx context.Context, id uuid.UUID) (Approval, error) {
	row := q.db.QueryRow(ctx, getApproval, id)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepSeq,
		&i.ToolCallID,
		&i.ToolName,
		&i.Args,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, agent_id, conversation_id, user_id, trigger_id, status, request, tool_policies, max_steps, step_count, first_message_id, cost_usd, error, heartbeat_at, owner_pid, started_at, ended_at, created_at, updated_at FROM agent_runs WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id uuid.UUID) (AgentRun, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ConversationID,
		&i.UserID,
		&i.TriggerID,
		&i.Status,
		&i.Request,
		&i.ToolPolicies,
		&i.MaxSteps,
		&i.StepCount,
		&i.FirstMessageID,
		&i.CostUsd,
		&i.Error,
		&i.HeartbeatAt,
		&i.OwnerPid,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrigger = `-- name: GetTrigger :one
SELECT id, agent_id, kind, spec, secret_hash, enabled, created_at, name, next_run_at, last_run_at, last_error FROM agent_triggers WHERE id = $1
`

func (q *Queries) GetTrigger(ctx context.Context, id uuid.UUID) (AgentTrigger, error) {
	row := q.db.QueryRow(ctx, getTrigger, id)
	var i AgentTrigger
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Kind,
		&i.Spec,
		&i.SecretHash,
		&i.Enabled,
		&i.CreatedAt,
		&i.Name,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastError,
	)
	return i, err
}

const heartbeatRun = `-- name: HeartbeatRun :exec
UPDATE agent_runs SET heartbeat_at = now() WHERE id = $1 AND owner_pid = $2
`

type HeartbeatRunParams struct {
	ID       uuid.UUID `json:"id"`
	OwnerPid *string   `json:"owner_pid"`
}

func (q *Queries) HeartbeatRun(ctx context.Context, arg HeartbeatRunParams) error {
	_, err := q.db.Exec(ctx, heartbeatRun, arg.ID, arg.OwnerPid)
	return err
}

const insertStep = `-- name: InsertStep :one
INSERT INTO agent_steps (run_id, seq, kind, input, checkpoint) VALUES ($1, $2, $3, $4, $5) RETURNING id, run_id, seq, kind, input, output, checkpoint, usage, error, started_at, ended_at
`

type InsertStepParams struct {
	RunID      uuid.UUID       `json:"run_id"`
	Seq        int32           `json:"seq"`
	Kind       string          `json:"kind"`
	Input      json.RawMessage `json:"input"`
	Checkpoint json.RawMessage `json:"checkpoint"`
}

func (q *Queries) InsertStep(ctx context.Context, arg InsertStepParams) (AgentStep, error) {
	row := q.db.QueryRow(ctx, insertStep,
		arg.RunID,
		arg.Seq,
		arg.Kind,
		arg.Input,
		arg.Checkpoint,
	)
	var i AgentStep
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Seq,
		&i.Kind,
		&i.Input,
		&i.Output,
		&i.Checkpoint,
		&i.Usage,
		&i.Error,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const lastStep = `-- name: LastStep :one
SELECT id, run_id, seq, kind, input, output, checkpoint, usage, error, started_at, ended_at FROM agent_steps WHERE run_id = $1 ORDER BY seq DESC LIMIT 1
`

func (q *Queries) LastStep(ctx context.Context, runID uuid.UUID) (AgentStep, error) {
	row := q.db.QueryRow(ctx, lastStep, runID)
	var i AgentStep
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Seq,
		&i.Kind,
		&i.Input,
		&i.Output,
		&i.Checkpoint,
		&i.Usage,
		&i.Error,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const latestRunForConversation = `-- name: LatestRunForConversation :one
SELECT id, agent_id, conversation_id, user_id, trigger_id, status, request, tool_policies, max_steps, step_count, first_message_id, cost_usd, error, heartbeat_at, owner_pid, started_at, ended_at, created_at, updated_at FROM agent_runs WHERE conversation_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) LatestRunForConversation(ctx context.Context, conversationID uuid.UUID) (AgentRun, error) {
	row := q.db.QueryRow(ctx, latestRunForConversation, conversationID)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ConversationID,
		&i.UserID,
		&i.TriggerID,
		&i.Status,
		&i.Request,
		&i.ToolPolicies,
		&i.MaxSteps,
		&i.StepCount,
		&i.FirstMessageID,
		&i.CostUsd,
		&i.Error,
		&i.HeartbeatAt,
		&i.OwnerPid,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentsForUser = `-- name: ListAgentsForUser :many
SELECT id, owner_id, name, goal, system_prompt, model_policy, tool_allowlist, tool_policies, mcp_servers, memory_config, max_steps, enabled, created_at, updated_at, project_id, last_run_at FROM agents WHERE owner_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAgentsForUser(ctx context.Context, ownerID uuid.UUID) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgentsForUser, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Goal,
			&i.SystemPrompt,
			&i.ModelPolicy,
			&i.ToolAllowlist,
			&i.ToolPolicies,
			&i.McpServers,
			&i.MemoryConfig,
			&i.MaxSteps,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectID,
			&i.LastRunAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovalsForRun = `-- name: ListApprovalsForRun :many
SELECT id, run_id, step_seq, tool_call_id, tool_name, args, status, decided_by, decided_at, note, created_at FROM approvals WHERE run_id = $1 ORDER BY created_at
`

func (q *Queries) ListApprovalsForRun(ctx context.Context, runID uuid.UUID) ([]Approval, error) {
	rows, err := q.db.Query(ctx, listApprovalsForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Approval{}
	for rows.Next() {
		var i Approval
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StepSeq,
			&i.ToolCallID,
			&i.ToolName,
			&i.Args,
			&i.Status,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueCronTriggers = `-- name: ListDueCronTriggers :many
SELECT t.id, t.agent_id, t.kind, t.spec, t.secret_hash, t.enabled, t.created_at, t.name, t.next_run_at, t.last_run_at, t.last_error FROM agent_triggers t JOIN agents a ON a.id = t.agent_id
WHERE t.enabled AND a.enabled AND t.kind = 'cron' AND t.next_run_at IS NOT NULL AND t.next_run_at <= now()
ORDER BY t.next_run_at LIMIT 50
`

func (q *Queries) ListDueCronTriggers(ctx context.Context) ([]AgentTrigger, error) {
	rows, err := q.db.Query(ctx, listDueCronTriggers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTrigger{}
	for rows.Next() {
		var i AgentTrigger
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Kind,
			&i.Spec,
			&i.SecretHash,
			&i.Enabled,
			&i.CreatedAt,
			&i.Name,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBySeq = `-- name: ListMessagesBySeq :many
SELECT id, conversation_id, seq, role, parts, endpoint_id, model, usage, finish_reason, parent_id, created_at FROM messages WHERE conversation_id = $1 AND seq > $2 AND seq <= $3 ORDER BY seq
`

type ListMessagesBySeqParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	Seq            int64     `json:"seq"`
	Seq_2          int64     `json:"seq_2"`
}

func (q *Queries) ListMessagesBySeq(ctx context.Context, arg ListMessagesBySeqParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesBySeq, arg.ConversationID, arg.Seq, arg.Seq_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Seq,
			&i.Role,
			&i.Parts,
			&i.EndpointID,
			&i.Model,
			&i.Usage,
			&i.FinishReason,
			&i.ParentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingApprovals = `-- name: ListPendingApprovals :many
SELECT id, run_id, step_seq, tool_call_id, tool_name, args, status, decided_by, decided_at, note, created_at FROM approvals WHERE run_id = $1 AND status = 'pending' ORDER BY created_at
`

func (q *Queries) ListPendingApprovals(ctx context.Context, runID uuid.UUID) ([]Approval, error) {
	rows, err := q.db.Query(ctx, listPendingApprovals, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Approval{}
	for rows.Next() {
		var i Approval
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StepSeq,
			&i.ToolCallID,
			&i.ToolName,
			&i.Args,
			&i.Status,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingApprovalsForAgent = `-- name: ListPendingApprovalsForAgent :many
SELECT a.id, a.run_id, a.step_seq, a.tool_call_id, a.tool_name, a.args, a.status, a.decided_by, a.decided_at, a.note, a.created_at FROM approvals a JOIN agent_runs r ON r.id = a.run_id
WHERE r.agent_id = $1 AND a.status = 'pending' ORDER BY a.created_at DESC
`

func (q *Queries) ListPendingApprovalsForAgent(ctx context.Context, agentID uuid.NullUUID) ([]Approval, error) {
	rows, err := q.db.Query(ctx, listPendingApprovalsForAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Approval{}
	for rows.Next() {
		var i Approval
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StepSeq,
			&i.ToolCallID,
			&i.ToolName,
			&i.Args,
			&i.Status,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingApprovalsForUser = `-- name: ListPendingApprovalsForUser :many
SELECT a.id, a.run_id, a.step_seq, a.tool_call_id, a.tool_name, a.args, a.status, a.decided_by, a.decided_at, a.note, a.created_at FROM approvals a JOIN agent_runs r ON r.id = a.run_id
WHERE r.user_id = $1 AND a.status = 'pending' ORDER BY a.created_at DESC
`

func (q *Queries) ListPendingApprovalsForUser(ctx context.Context, userID uuid.NullUUID) ([]Approval, error) {
	rows, err := q.db.Query(ctx, listPendingApprovalsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Approval{}
	for rows.Next() {
		var i Approval
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StepSeq,
			&i.ToolCallID,
			&i.ToolName,
			&i.Args,
			&i.Status,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuedRuns = `-- name: ListQueuedRuns :many
SELECT id, agent_id, conversation_id, user_id, trigger_id, status, request, tool_policies, max_steps, step_count, first_message_id, cost_usd, error, heartbeat_at, owner_pid, started_at, ended_at, created_at, updated_at FROM agent_runs WHERE status = 'queued' ORDER BY created_at LIMIT 20
`

func (q *Queries) ListQueuedRuns(ctx context.Context) ([]AgentRun, error) {
	rows, err := q.db.Query(ctx, listQueuedRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentRun{}
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ConversationID,
			&i.UserID,
			&i.TriggerID,
			&i.Status,
			&i.Request,
			&i.ToolPolicies,
			&i.MaxSteps,
			&i.StepCount,
			&i.FirstMessageID,
			&i.CostUsd,
			&i.Error,
			&i.HeartbeatAt,
			&i.OwnerPid,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoPushTriggers = `-- name: ListRepoPushTriggers :many
SELECT t.id, t.agent_id, t.kind, t.spec, t.secret_hash, t.enabled, t.created_at, t.name, t.next_run_at, t.last_run_at, t.last_error FROM agent_triggers t JOIN agents a ON a.id = t.agent_id
WHERE t.enabled AND a.enabled AND t.kind = 'repo_push'
ORDER BY t.created_at
`

func (q *Queries) ListRepoPushTriggers(ctx context.Context) ([]AgentTrigger, error) {
	rows, err := q.db.Query(ctx, listRepoPushTriggers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTrigger{}
	for rows.Next() {
		var i AgentTrigger
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Kind,
			&i.Spec,
			&i.SecretHash,
			&i.Enabled,
			&i.CreatedAt,
			&i.Name,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsForAgent = `-- name: ListRunsForAgent :many
SELECT id, agent_id, conversation_id, user_id, trigger_id, status, request, tool_policies, max_steps, step_count, first_message_id, cost_usd, error, heartbeat_at, owner_pid, started_at, ended_at, created_at, updated_at FROM agent_runs WHERE agent_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListRunsForAgentParams struct {
	AgentID uuid.NullUUID `json:"agent_id"`
	Limit   int32         `json:"limit"`
}

func (q *Queries) ListRunsForAgent(ctx context.Context, arg ListRunsForAgentParams) ([]AgentRun, error) {
	rows, err := q.db.Query(ctx, listRunsForAgent, arg.AgentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentRun{}
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ConversationID,
			&i.UserID,
			&i.TriggerID,
			&i.Status,
			&i.Request,
			&i.ToolPolicies,
			&i.MaxSteps,
			&i.StepCount,
			&i.FirstMessageID,
			&i.CostUsd,
			&i.Error,
			&i.HeartbeatAt,
			&i.OwnerPid,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsForConversation = `-- name: ListRunsForConversation :many
SELECT id, agent_id, conversation_id, user_id, trigger_id, status, request, tool_policies, max_steps, step_count, first_message_id, cost_usd, error, heartbeat_at, owner_pid, started_at, ended_at, created_at, updated_at FROM agent_runs WHERE conversation_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListRunsForConversationParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	Limit          int32     `json:"limit"`
}

func (q *Queries) ListRunsForConversation(ctx context.Context, arg ListRunsForConversationParams) ([]AgentRun, error) {
	rows, err := q.db.Query(ctx, listRunsForConversation, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentRun{}
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ConversationID,
			&i.UserID,
			&i.TriggerID,
			&i.Status,
			&i.Request,
			&i.ToolPolicies,
			&i.MaxSteps,
			&i.StepCount,
			&i.FirstMessageID,
			&i.CostUsd,
			&i.Error,
			&i.HeartbeatAt,
			&i.OwnerPid,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleRuns = `-- name: ListStaleRuns :many
SELECT id, agent_id, conversation_id, user_id, trigger_id, status, request, tool_policies, max_steps, step_count, first_message_id, cost_usd, error, heartbeat_at, owner_pid, started_at, ended_at, created_at, updated_at FROM agent_runs WHERE status = 'running' AND heartbeat_at < now() - interval '90 seconds' ORDER BY heartbeat_at LIMIT 20
`

func (q *Queries) ListStaleRuns(ctx context.Context) ([]AgentRun, error) {
	rows, err := q.db.Query(ctx, listStaleRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentRun{}
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ConversationID,
			&i.UserID,
			&i.TriggerID,
			&i.Status,
			&i.Request,
			&i.ToolPolicies,
			&i.MaxSteps,
			&i.StepCount,
			&i.FirstMessageID,
			&i.CostUsd,
			&i.Error,
			&i.HeartbeatAt,
			&i.OwnerPid,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSteps = `-- name: ListSteps :many
SELECT id, run_id, seq, kind, input, output, checkpoint, usage, error, started_at, ended_at FROM agent_steps WHERE run_id = $1 ORDER BY seq
`

func (q *Queries) ListSteps(ctx context.Context, runID uuid.UUID) ([]AgentStep, error) {
	rows, err := q.db.Query(ctx, listSteps, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentStep{}
	for rows.Next() {
		var i AgentStep
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Seq,
			&i.Kind,
			&i.Input,
			&i.Output,
			&i.Checkpoint,
			&i.Usage,
			&i.Error,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTriggersForAgent = `-- name: ListTriggersForAgent :many
SELECT id, agent_id, kind, spec, secret_hash, enabled, created_at, name, next_run_at, last_run_at, last_error FROM agent_triggers WHERE agent_id = $1 ORDER BY created_at
`

func (q *Queries) ListTriggersForAgent(ctx context.Context, agentID uuid.UUID) ([]AgentTrigger, error) {
	rows, err := q.db.Query(ctx, listTriggersForAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTrigger{}
	for rows.Next() {
		var i AgentTrigger
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Kind,
			&i.Spec,
			&i.SecretHash,
			&i.Enabled,
			&i.CreatedAt,
			&i.Name,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextStepSeq = `-- name: NextStepSeq :one
SELECT COALESCE(MAX(seq), 0) + 1 FROM agent_steps WHERE run_id = $1
`

func (q *Queries) NextStepSeq(ctx context.Context, runID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextStepSeq, runID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const pauseRunForApproval = `-- name: PauseRunForApproval :one
UPDATE agent_runs SET status = 'paused_approval'
WHERE agent_runs.id = $1 AND agent_runs.status = 'running'
  AND EXISTS (SELECT 1 FROM approvals WHERE run_id = $1 AND status = 'pending')
RETURNING agent_runs.id
`

// PauseRunForApproval parks a running run only while a decision is still
// outstanding. A decision that landed while the batch was finishing leaves
// no pending row, the update changes nothing, and the caller runs the
// decided calls instead of pausing a run nobody will wake.
func (q *Queries) PauseRunForApproval(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, pauseRunForApproval, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const requeueRunAfterApproval = `-- name: RequeueRunAfterApproval :one
UPDATE agent_runs SET status = 'queued'
WHERE agent_runs.id = $1 AND agent_runs.status = 'paused_approval'
  AND NOT EXISTS (SELECT 1 FROM approvals WHERE run_id = $1 AND status = 'pending')
RETURNING agent_runs.id
`

// RequeueRunAfterApproval hands a parked run back to the worker once no
// decision is outstanding. Only a parked run is moved: one still 'running'
// is finishing its batch and will see the decision itself.
func (q *Queries) RequeueRunAfterApproval(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, requeueRunAfterApproval, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const resumeRunAfterApproval = `-- name: ResumeRunAfterApproval :one
UPDATE agent_runs SET status = 'running', owner_pid = $2, heartbeat_at = now()
WHERE agent_runs.id = $1 AND agent_runs.status = 'paused_approval'
RETURNING id, agent_id, conversation_id, user_id, trigger_id, status, request, tool_policies, max_steps, step_count, first_message_id, cost_usd, error, heartbeat_at, owner_pid, started_at, ended_at, created_at, updated_at
`

type ResumeRunAfterApprovalParams struct {
	ID       uuid.UUID `json:"id"`
	OwnerPid *string   `json:"owner_pid"`
}

func (q *Queries) ResumeRunAfterApproval(ctx context.Context, arg ResumeRunAfterApprovalParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, resumeRunAfterApproval, arg.ID, arg.OwnerPid)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ConversationID,
		&i.UserID,
		&i.TriggerID,
		&i.Status,
		&i.Request,
		&i.ToolPolicies,
		&i.MaxSteps,
		&i.StepCount,
		&i.FirstMessageID,
		&i.CostUsd,
		&i.Error,
		&i.HeartbeatAt,
		&i.OwnerPid,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setAgentEnabled = `-- name: SetAgentEnabled :exec
UPDATE agents SET enabled = $2 WHERE id = $1
`

type SetAgentEnabledParams struct {
	ID      uuid.UUID `json:"id"`
	Enabled bool      `json:"enabled"`
}

func (q *Queries) SetAgentEnabled(ctx context.Context, arg SetAgentEnabledParams) error {
	_, err := q.db.Exec(ctx, setAgentEnabled, arg.ID, arg.Enabled)
	return err
}

const setConversationAgent = `-- name: SetConversationAgent :exec
UPDATE conversations SET agent_id = $2 WHERE id = $1
`

type SetConversationAgentParams struct {
	ID      uuid.UUID     `json:"id"`
	AgentID uuid.NullUUID `json:"agent_id"`
}

func (q *Queries) SetConversationAgent(ctx context.Context, arg SetConversationAgentParams) error {
	_, err := q.db.Exec(ctx, setConversationAgent, arg.ID, arg.AgentID)
	return err
}

const setRunFirstMessage = `-- name: SetRunFirstMessage :exec
UPDATE agent_runs SET first_message_id = $2 WHERE id = $1 AND first_message_id IS NULL
`

type SetRunFirstMessageParams struct {
	ID             uuid.UUID     `json:"id"`
	FirstMessageID uuid.NullUUID `json:"first_message_id"`
}

func (q *Queries) SetRunFirstMessage(ctx context.Context, arg SetRunFirstMessageParams) error {
	_, err := q.db.Exec(ctx, setRunFirstMessage, arg.ID, arg.FirstMessageID)
	return err
}

const setRunStatus = `-- name: SetRunStatus :exec
UPDATE agent_runs SET status = $2, error = $3,
    ended_at = CASE WHEN $2 IN ('done','failed','cancelled') THEN now() ELSE ended_at END,
    started_at = COALESCE(started_at, CASE WHEN $2 = 'running' THEN now() ELSE NULL END)
WHERE id = $1
`

type SetRunStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
	Error  *string   `json:"error"`
}

func (q *Queries) SetRunStatus(ctx context.Context, arg SetRunStatusParams) error {
	_, err := q.db.Exec(ctx, setRunStatus, arg.ID, arg.Status, arg.Error)
	return err
}

const setTriggerEnabled = `-- name: SetTriggerEnabled :exec
UPDATE agent_triggers SET enabled = $3 WHERE id = $1 AND agent_id = $2
`

type SetTriggerEnabledParams struct {
	ID      uuid.UUID `json:"id"`
	AgentID uuid.UUID `json:"agent_id"`
	Enabled bool      `json:"enabled"`
}

func (q *Queries) SetTriggerEnabled(ctx context.Context, arg SetTriggerEnabledParams) error {
	_, err := q.db.Exec(ctx, setTriggerEnabled, arg.ID, arg.AgentID, arg.Enabled)
	return err
}

const setTriggerFired = `-- name: SetTriggerFired :exec
UPDATE agent_triggers SET last_run_at = now(), next_run_at = $2, last_error = $3 WHERE id = $1
`

type SetTriggerFiredParams struct {
	ID        uuid.UUID  `json:"id"`
	NextRunAt *time.Time `json:"next_run_at"`
	LastError *string    `json:"last_error"`
}

func (q *Queries) SetTriggerFired(ctx context.Context, arg SetTriggerFiredParams) error {
	_, err := q.db.Exec(ctx, setTriggerFired, arg.ID, arg.NextRunAt, arg.LastError)
	return err
}

const touchAgentRun = `-- name: TouchAgentRun :exec
UPDATE agents SET last_run_at = now() WHERE id = $1
`

func (q *Queries) TouchAgentRun(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAgentRun, id)
	return err
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents SET name = $2, goal = $3, system_prompt = $4, model_policy = $5, tool_allowlist = $6, tool_policies = $7, max_steps = $8, enabled = $9, project_id = $10
WHERE id = $1 RETURNING id, owner_id, name, goal, system_prompt, model_policy, tool_allowlist, tool_policies, mcp_servers, memory_config, max_steps, enabled, created_at, updated_at, project_id, last_run_at
`

type UpdateAgentParams struct {
	ID            uuid.UUID       `json:"id"`
	Name          string          `json:"name"`
	Goal          string          `json:"goal"`
	SystemPrompt  string          `json:"system_prompt"`
	ModelPolicy   json.RawMessage `json:"model_policy"`
	ToolAllowlist []string        `json:"tool_allowlist"`
	ToolPolicies  json.RawMessage `json:"tool_policies"`
	MaxSteps      int32           `json:"max_steps"`
	Enabled       bool            `json:"enabled"`
	ProjectID     uuid.NullUUID   `json:"project_id"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		arg.ID,
		arg.Name,
		arg.Goal,
		arg.SystemPrompt,
		arg.ModelPolicy,
		arg.ToolAllowlist,
		arg.ToolPolicies,
		arg.MaxSteps,
		arg.Enabled,
		arg.ProjectID,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Goal,
		&i.SystemPrompt,
		&i.ModelPolicy,
		&i.ToolAllowlist,
		&i.ToolPolicies,
		&i.McpServers,
		&i.MemoryConfig,
		&i.MaxSteps,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.LastRunAt,
	)
	return i, err
}

const updateStepCheckpoint = `-- name: UpdateStepCheckpoint :exec
UPDATE agent_steps SET checkpoint = $2 WHERE id = $1
`

type UpdateStepCheckpointParams struct {
	ID         uuid.UUID       `json:"id"`
	Checkpoint json.RawMessage `json:"checkpoint"`
}

func (q *Queries) UpdateStepCheckpoint(ctx context.Context, arg UpdateStepCheckpointParams) error {
	_, err := q.db.Exec(ctx, updateStepCheckpoint, arg.ID, arg.Checkpoint)
	return err
}
