// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package store

import (
	"context"
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const consumeMagicLink = `-- name: ConsumeMagicLink :one
UPDATE magic_links SET used_at = now()
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
RETURNING id, user_id, token_hash, created_at, expires_at, used_at
`

func (q *Queries) ConsumeMagicLink(ctx context.Context, tokenHash []byte) (MagicLink, error) {
	row := q.db.QueryRow(ctx, consumeMagicLink, tokenHash)
	var i MagicLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, name, prefix, key_hash, scopes, default_policy, budget_id)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, user_id, name, prefix, key_hash, scopes, default_policy, budget_id, created_at, last_used_at, revoked_at
`

type CreateAPIKeyParams struct {
	UserID        uuid.UUID     `json:"user_id"`
	Name          string        `json:"name"`
	Prefix        string        `json:"prefix"`
	KeyHash       []byte        `json:"key_hash"`
	Scopes        []string      `json:"scopes"`
	DefaultPolicy string        `json:"default_policy"`
	BudgetID      uuid.NullUUID `json:"budget_id"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.UserID,
		arg.Name,
		arg.Prefix,
		arg.KeyHash,
		arg.Scopes,
		arg.DefaultPolicy,
		arg.BudgetID,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.Scopes,
		&i.DefaultPolicy,
		&i.BudgetID,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (email, token_hash, invited_by, role, expires_at)
VALUES ($1, $2, $3, $4, $5) RETURNING id, email, token_hash, invited_by, role, created_at, expires_at, used_at, used_by
`

type CreateInviteParams struct {
	Email     string        `json:"email"`
	TokenHash []byte        `json:"token_hash"`
	InvitedBy uuid.NullUUID `json:"invited_by"`
	Role      string        `json:"role"`
	ExpiresAt time.Time     `json:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.Email,
		arg.TokenHash,
		arg.InvitedBy,
		arg.Role,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TokenHash,
		&i.InvitedBy,
		&i.Role,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedBy,
	)
	return i, err
}

const createMagicLink = `-- name: CreateMagicLink :one
INSERT INTO magic_links (user_id, token_hash, expires_at) VALUES ($1, $2, $3) RETURNING id, user_id, token_hash, created_at, expires_at, used_at
`

type CreateMagicLinkParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash []byte    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) (MagicLink, error) {
	row := q.db.QueryRow(ctx, createMagicLink, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i MagicLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const createPasskey = `-- name: CreatePasskey :one
INSERT INTO passkeys (user_id, credential_id, public_key, attestation_type, transports, aaguid, sign_count, backup_eligible, backup_state, name)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id, user_id, credential_id, public_key, attestation_type, transports, aaguid, sign_count, backup_eligible, backup_state, name, created_at, last_used_at
`

type CreatePasskeyParams struct {
	UserID          uuid.UUID `json:"user_id"`
	CredentialID    []byte    `json:"credential_id"`
	PublicKey       []byte    `json:"public_key"`
	AttestationType string    `json:"attestation_type"`
	Transports      []string  `json:"transports"`
	Aaguid          []byte    `json:"aaguid"`
	SignCount       int64     `json:"sign_count"`
	BackupEligible  bool      `json:"backup_eligible"`
	BackupState     bool      `json:"backup_state"`
	Name            string    `json:"name"`
}

func (q *Queries) CreatePasskey(ctx context.Context, arg CreatePasskeyParams) (Passkey, error) {
	row := q.db.QueryRow(ctx, createPasskey,
		arg.UserID,
		arg.CredentialID,
		arg.PublicKey,
		arg.AttestationType,
		arg.Transports,
		arg.Aaguid,
		arg.SignCount,
		arg.BackupEligible,
		arg.BackupState,
		arg.Name,
	)
	var i Passkey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.AttestationType,
		&i.Transports,
		&i.Aaguid,
		&i.SignCount,
		&i.BackupEligible,
		&i.BackupState,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, expires_at, user_agent, ip) VALUES ($1, $2, $3, $4, $5) RETURNING id, user_id, token_hash, created_at, expires_at, user_agent, ip, revoked_at
`

type CreateSessionParams struct {
	UserID    uuid.UUID     `json:"user_id"`
	TokenHash []byte        `json:"token_hash"`
	ExpiresAt time.Time     `json:"expires_at"`
	UserAgent string        `json:"user_agent"`
	Ip        *netip.Prefix `json:"ip"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UserAgent,
		&i.Ip,
		&i.RevokedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, display_name, role) VALUES ($1, $2, $3) RETURNING id, email, display_name, role, created_at, disabled_at, training_consent
`

type CreateUserParams struct {
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
	Role        string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.DisplayName, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.TrainingConsent,
	)
	return i, err
}

const createWebAuthnSession = `-- name: CreateWebAuthnSession :one
INSERT INTO webauthn_sessions (user_id, kind, data, expires_at) VALUES ($1, $2, $3, $4) RETURNING id, user_id, kind, data, created_at, expires_at
`

type CreateWebAuthnSessionParams struct {
	UserID    uuid.NullUUID   `json:"user_id"`
	Kind      string          `json:"kind"`
	Data      json.RawMessage `json:"data"`
	ExpiresAt time.Time       `json:"expires_at"`
}

func (q *Queries) CreateWebAuthnSession(ctx context.Context, arg CreateWebAuthnSessionParams) (WebauthnSession, error) {
	row := q.db.QueryRow(ctx, createWebAuthnSession,
		arg.UserID,
		arg.Kind,
		arg.Data,
		arg.ExpiresAt,
	)
	var i WebauthnSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Data,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deletePasskey = `-- name: DeletePasskey :exec
DELETE FROM passkeys WHERE id = $1 AND user_id = $2
`

type DeletePasskeyParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePasskey(ctx context.Context, arg DeletePasskeyParams) error {
	_, err := q.db.Exec(ctx, deletePasskey, arg.ID, arg.UserID)
	return err
}

const deleteWebAuthnSession = `-- name: DeleteWebAuthnSession :exec
DELETE FROM webauthn_sessions WHERE id = $1
`

func (q *Queries) DeleteWebAuthnSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWebAuthnSession, id)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT k.id, k.user_id, k.name, k.prefix, k.key_hash, k.scopes, k.default_policy, k.budget_id, k.created_at, k.last_used_at, k.revoked_at, u.email, u.role
FROM api_keys k JOIN users u ON u.id = k.user_id
WHERE k.key_hash = $1 AND k.revoked_at IS NULL AND u.disabled_at IS NULL
`

type GetAPIKeyByHashRow struct {
	ID            uuid.UUID     `json:"id"`
	UserID        uuid.UUID     `json:"user_id"`
	Name          string        `json:"name"`
	Prefix        string        `json:"prefix"`
	KeyHash       []byte        `json:"key_hash"`
	Scopes        []string      `json:"scopes"`
	DefaultPolicy string        `json:"default_policy"`
	BudgetID      uuid.NullUUID `json:"budget_id"`
	CreatedAt     time.Time     `json:"created_at"`
	LastUsedAt    *time.Time    `json:"last_used_at"`
	RevokedAt     *time.Time    `json:"revoked_at"`
	Email         string        `json:"email"`
	Role          string        `json:"role"`
}

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash []byte) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.Scopes,
		&i.DefaultPolicy,
		&i.BudgetID,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.Email,
		&i.Role,
	)
	return i, err
}

const getInviteByTokenHash = `-- name: GetInviteByTokenHash :one
SELECT id, email, token_hash, invited_by, role, created_at, expires_at, used_at, used_by FROM invites WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
`

func (q *Queries) GetInviteByTokenHash(ctx context.Context, tokenHash []byte) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByTokenHash, tokenHash)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TokenHash,
		&i.InvitedBy,
		&i.Role,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedBy,
	)
	return i, err
}

const getPasskeyByCredentialID = `-- name: GetPasskeyByCredentialID :one
SELECT id, user_id, credential_id, public_key, attestation_type, transports, aaguid, sign_count, backup_eligible, backup_state, name, created_at, last_used_at FROM passkeys WHERE credential_id = $1
`

func (q *Queries) GetPasskeyByCredentialID(ctx context.Context, credentialID []byte) (Passkey, error) {
	row := q.db.QueryRow(ctx, getPasskeyByCredentialID, credentialID)
	var i Passkey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.AttestationType,
		&i.Transports,
		&i.Aaguid,
		&i.SignCount,
		&i.BackupEligible,
		&i.BackupState,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT s.id, s.user_id, s.token_hash, s.created_at, s.expires_at, s.user_agent, s.ip, s.revoked_at, u.email, u.display_name, u.role
FROM sessions s JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.revoked_at IS NULL AND s.expires_at > now() AND u.disabled_at IS NULL
`

type GetSessionByTokenHashRow struct {
	ID          uuid.UUID     `json:"id"`
	UserID      uuid.UUID     `json:"user_id"`
	TokenHash   []byte        `json:"token_hash"`
	CreatedAt   time.Time     `json:"created_at"`
	ExpiresAt   time.Time     `json:"expires_at"`
	UserAgent   string        `json:"user_agent"`
	Ip          *netip.Prefix `json:"ip"`
	RevokedAt   *time.Time    `json:"revoked_at"`
	Email       string        `json:"email"`
	DisplayName string        `json:"display_name"`
	Role        string        `json:"role"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UserAgent,
		&i.Ip,
		&i.RevokedAt,
		&i.Email,
		&i.DisplayName,
		&i.Role,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, role, created_at, disabled_at, training_consent FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.TrainingConsent,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, role, created_at, disabled_at, training_consent FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.TrainingConsent,
	)
	return i, err
}

const getWebAuthnSession = `-- name: GetWebAuthnSession :one
SELECT id, user_id, kind, data, created_at, expires_at FROM webauthn_sessions WHERE id = $1 AND expires_at > now()
`

func (q *Queries) GetWebAuthnSession(ctx context.Context, id uuid.UUID) (WebauthnSession, error) {
	row := q.db.QueryRow(ctx, getWebAuthnSession, id)
	var i WebauthnSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Data,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT id, user_id, name, prefix, key_hash, scopes, default_policy, budget_id, created_at, last_used_at, revoked_at FROM api_keys WHERE user_id = $1 AND revoked_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByUser(ctx context.Context, userID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.KeyHash,
			&i.Scopes,
			&i.DefaultPolicy,
			&i.BudgetID,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvites = `-- name: ListInvites :many
SELECT id, email, token_hash, invited_by, role, created_at, expires_at, used_at, used_by FROM invites ORDER BY created_at DESC
`

func (q *Queries) ListInvites(ctx context.Context) ([]Invite, error) {
	rows, err := q.db.Query(ctx, listInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invite{}
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.TokenHash,
			&i.InvitedBy,
			&i.Role,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.UsedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPasskeysByUser = `-- name: ListPasskeysByUser :many
SELECT id, user_id, credential_id, public_key, attestation_type, transports, aaguid, sign_count, backup_eligible, backup_state, name, created_at, last_used_at FROM passkeys WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListPasskeysByUser(ctx context.Context, userID uuid.UUID) ([]Passkey, error) {
	rows, err := q.db.Query(ctx, listPasskeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Passkey{}
	for rows.Next() {
		var i Passkey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.PublicKey,
			&i.AttestationType,
			&i.Transports,
			&i.Aaguid,
			&i.SignCount,
			&i.BackupEligible,
			&i.BackupState,
			&i.Name,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, display_name, role, created_at, disabled_at, training_consent FROM users ORDER BY created_at
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.CreatedAt,
			&i.DisabledAt,
			&i.TrainingConsent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeExpiredWebAuthnSessions = `-- name: PurgeExpiredWebAuthnSessions :exec
DELETE FROM webauthn_sessions WHERE expires_at <= now()
`

func (q *Queries) PurgeExpiredWebAuthnSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, purgeExpiredWebAuthnSessions)
	return err
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys SET revoked_at = now() WHERE id = $1 AND user_id = $2
`

type RevokeAPIKeyParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.UserID)
	return err
}

const revokeAllSessionsForUser = `-- name: RevokeAllSessionsForUser :exec
UPDATE sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllSessionsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllSessionsForUser, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}

const updatePasskeyAfterLogin = `-- name: UpdatePasskeyAfterLogin :exec
UPDATE passkeys SET sign_count = $2, backup_state = $3, last_used_at = now() WHERE id = $1
`

type UpdatePasskeyAfterLoginParams struct {
	ID          uuid.UUID `json:"id"`
	SignCount   int64     `json:"sign_count"`
	BackupState bool      `json:"backup_state"`
}

func (q *Queries) UpdatePasskeyAfterLogin(ctx context.Context, arg UpdatePasskeyAfterLoginParams) error {
	_, err := q.db.Exec(ctx, updatePasskeyAfterLogin, arg.ID, arg.SignCount, arg.BackupState)
	return err
}

const useInvite = `-- name: UseInvite :exec
UPDATE invites SET used_at = now(), used_by = $2 WHERE id = $1
`

type UseInviteParams struct {
	ID     uuid.UUID     `json:"id"`
	UsedBy uuid.NullUUID `json:"used_by"`
}

func (q *Queries) UseInvite(ctx context.Context, arg UseInviteParams) error {
	_, err := q.db.Exec(ctx, useInvite, arg.ID, arg.UsedBy)
	return err
}
