// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ccjobs.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const getCCJob = `-- name: GetCCJob :one
SELECT id, user_id, target, session, "window", cwd, lane, model, source, status, started_at, seen_at, ended_at, created_at, updated_at FROM cc_jobs WHERE id = $1
`

func (q *Queries) GetCCJob(ctx context.Context, id string) (CcJob, error) {
	row := q.db.QueryRow(ctx, getCCJob, id)
	var i CcJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Target,
		&i.Session,
		&i.Window,
		&i.Cwd,
		&i.Lane,
		&i.Model,
		&i.Source,
		&i.Status,
		&i.StartedAt,
		&i.SeenAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCCLaunchCount = `-- name: GetCCLaunchCount :one
SELECT count FROM cc_launch_counter WHERE week = $1
`

func (q *Queries) GetCCLaunchCount(ctx context.Context, week time.Time) (int32, error) {
	row := q.db.QueryRow(ctx, getCCLaunchCount, week)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const incrementCCLaunchCounter = `-- name: IncrementCCLaunchCounter :one

INSERT INTO cc_launch_counter (week, count) VALUES ($1, 1)
ON CONFLICT (week) DO UPDATE SET count = cc_launch_counter.count + 1, updated_at = now()
RETURNING count
`

// Weekly launch counter (§6.4, spec M6). week is the Monday 00:00 UTC
// the launch falls in.
func (q *Queries) IncrementCCLaunchCounter(ctx context.Context, week time.Time) (int32, error) {
	row := q.db.QueryRow(ctx, incrementCCLaunchCounter, week)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const insertCCRouteDecision = `-- name: InsertCCRouteDecision :one

INSERT INTO cc_route_decisions (user_id, conversation_id, prompt_sha256, features, lane, rule, reason, target, model, dry_run, job_id, run_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) RETURNING id, user_id, conversation_id, prompt_sha256, features, lane, rule, reason, target, model, dry_run, job_id, run_id, created_at
`

type InsertCCRouteDecisionParams struct {
	UserID         uuid.NullUUID   `json:"user_id"`
	ConversationID uuid.NullUUID   `json:"conversation_id"`
	PromptSha256   string          `json:"prompt_sha256"`
	Features       json.RawMessage `json:"features"`
	Lane           string          `json:"lane"`
	Rule           string          `json:"rule"`
	Reason         string          `json:"reason"`
	Target         *string         `json:"target"`
	Model          *string         `json:"model"`
	DryRun         bool            `json:"dry_run"`
	JobID          *string         `json:"job_id"`
	RunID          uuid.NullUUID   `json:"run_id"`
}

// Task router decision log (docs/CLAUDE_CODE_JOBS.md §6.4).
func (q *Queries) InsertCCRouteDecision(ctx context.Context, arg InsertCCRouteDecisionParams) (CcRouteDecision, error) {
	row := q.db.QueryRow(ctx, insertCCRouteDecision,
		arg.UserID,
		arg.ConversationID,
		arg.PromptSha256,
		arg.Features,
		arg.Lane,
		arg.Rule,
		arg.Reason,
		arg.Target,
		arg.Model,
		arg.DryRun,
		arg.JobID,
		arg.RunID,
	)
	var i CcRouteDecision
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConversationID,
		&i.PromptSha256,
		&i.Features,
		&i.Lane,
		&i.Rule,
		&i.Reason,
		&i.Target,
		&i.Model,
		&i.DryRun,
		&i.JobID,
		&i.RunID,
		&i.CreatedAt,
	)
	return i, err
}

const listCCJobs = `-- name: ListCCJobs :many
SELECT id, user_id, target, session, "window", cwd, lane, model, source, status, started_at, seen_at, ended_at, created_at, updated_at FROM cc_jobs ORDER BY started_at DESC LIMIT $1
`

func (q *Queries) ListCCJobs(ctx context.Context, limit int32) ([]CcJob, error) {
	rows, err := q.db.Query(ctx, listCCJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CcJob{}
	for rows.Next() {
		var i CcJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Target,
			&i.Session,
			&i.Window,
			&i.Cwd,
			&i.Lane,
			&i.Model,
			&i.Source,
			&i.Status,
			&i.StartedAt,
			&i.SeenAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCCJobsOpen = `-- name: ListCCJobsOpen :many
SELECT id, user_id, target, session, "window", cwd, lane, model, source, status, started_at, seen_at, ended_at, created_at, updated_at FROM cc_jobs WHERE status IN ('alive','dead','unknown') ORDER BY started_at DESC
`

func (q *Queries) ListCCJobsOpen(ctx context.Context) ([]CcJob, error) {
	rows, err := q.db.Query(ctx, listCCJobsOpen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CcJob{}
	for rows.Next() {
		var i CcJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Target,
			&i.Session,
			&i.Window,
			&i.Cwd,
			&i.Lane,
			&i.Model,
			&i.Source,
			&i.Status,
			&i.StartedAt,
			&i.SeenAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCCRouteDecisions = `-- name: ListCCRouteDecisions :many
SELECT id, user_id, conversation_id, prompt_sha256, features, lane, rule, reason, target, model, dry_run, job_id, run_id, created_at FROM cc_route_decisions ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListCCRouteDecisions(ctx context.Context, limit int32) ([]CcRouteDecision, error) {
	rows, err := q.db.Query(ctx, listCCRouteDecisions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CcRouteDecision{}
	for rows.Next() {
		var i CcRouteDecision
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ConversationID,
			&i.PromptSha256,
			&i.Features,
			&i.Lane,
			&i.Rule,
			&i.Reason,
			&i.Target,
			&i.Model,
			&i.DryRun,
			&i.JobID,
			&i.RunID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCCJobEnded = `-- name: MarkCCJobEnded :exec

UPDATE cc_jobs SET status = $2, ended_at = COALESCE(ended_at, now()), updated_at = now()
WHERE id = $1 AND status NOT IN ('killed','gone')
`

type MarkCCJobEndedParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

// MarkCCJobEnded closes a job: killed (reported by wsj) or gone (a refresh
// no longer found the window). A job that already ended keeps its status.
func (q *Queries) MarkCCJobEnded(ctx context.Context, arg MarkCCJobEndedParams) error {
	_, err := q.db.Exec(ctx, markCCJobEnded, arg.ID, arg.Status)
	return err
}

const markCCJobSeen = `-- name: MarkCCJobSeen :exec

UPDATE cc_jobs SET status = $2, seen_at = now(),
    ended_at = CASE WHEN $2 = 'dead' THEN COALESCE(ended_at, now()) ELSE NULL END,
    updated_at = now()
WHERE id = $1
`

type MarkCCJobSeenParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

// MarkCCJobSeen records what a refresh found: the window is listed and its
// pane is running (alive) or has exited (dead).
func (q *Queries) MarkCCJobSeen(ctx context.Context, arg MarkCCJobSeenParams) error {
	_, err := q.db.Exec(ctx, markCCJobSeen, arg.ID, arg.Status)
	return err
}

const upsertCCJob = `-- name: UpsertCCJob :one

INSERT INTO cc_jobs (id, user_id, target, session, "window", cwd, lane, model, source, status, started_at, seen_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, now())
ON CONFLICT (id) DO UPDATE SET
    target = EXCLUDED.target, session = EXCLUDED.session, "window" = EXCLUDED."window",
    cwd = EXCLUDED.cwd, lane = EXCLUDED.lane, model = COALESCE(EXCLUDED.model, cc_jobs.model),
    status = EXCLUDED.status, seen_at = now(),
    ended_at = CASE WHEN EXCLUDED.status = 'dead' THEN COALESCE(cc_jobs.ended_at, now()) ELSE NULL END,
    updated_at = now()
RETURNING cc_jobs.id, cc_jobs.user_id, cc_jobs.target, cc_jobs.session, cc_jobs."window", cc_jobs.cwd, cc_jobs.lane, cc_jobs.model, cc_jobs.source, cc_jobs.status, cc_jobs.started_at, cc_jobs.seen_at, cc_jobs.ended_at, cc_jobs.created_at, cc_jobs.updated_at, (xmax = 0) AS inserted
`

type UpsertCCJobParams struct {
	ID        string        `json:"id"`
	UserID    uuid.NullUUID `json:"user_id"`
	Target    string        `json:"target"`
	Session   string        `json:"session"`
	Window    string        `json:"window"`
	Cwd       string        `json:"cwd"`
	Lane      string        `json:"lane"`
	Model     *string       `json:"model"`
	Source    string        `json:"source"`
	Status    string        `json:"status"`
	StartedAt time.Time     `json:"started_at"`
}

type UpsertCCJobRow struct {
	CcJob    CcJob `json:"cc_job"`
	Inserted bool  `json:"inserted"`
}

// Job handles for the read-only web tab (§6.5). A report of a job that is
// already known refreshes its handle fields and liveness; it never moves
// the job to another user or source.
// inserted is true when this call created the row (xmax is 0 on a fresh
// tuple, non-zero on one ON CONFLICT updated), decided in the same
// statement so two reports of the same new job cannot both count it.
func (q *Queries) UpsertCCJob(ctx context.Context, arg UpsertCCJobParams) (UpsertCCJobRow, error) {
	row := q.db.QueryRow(ctx, upsertCCJob,
		arg.ID,
		arg.UserID,
		arg.Target,
		arg.Session,
		arg.Window,
		arg.Cwd,
		arg.Lane,
		arg.Model,
		arg.Source,
		arg.Status,
		arg.StartedAt,
	)
	var i UpsertCCJobRow
	err := row.Scan(
		&i.CcJob.ID,
		&i.CcJob.UserID,
		&i.CcJob.Target,
		&i.CcJob.Session,
		&i.CcJob.Window,
		&i.CcJob.Cwd,
		&i.CcJob.Lane,
		&i.CcJob.Model,
		&i.CcJob.Source,
		&i.CcJob.Status,
		&i.CcJob.StartedAt,
		&i.CcJob.SeenAt,
		&i.CcJob.EndedAt,
		&i.CcJob.CreatedAt,
		&i.CcJob.UpdatedAt,
		&i.Inserted,
	)
	return i, err
}
