// Package store owns the Postgres connection, migrations, and generated
// queries (sqlc). Blob storage lives in the blob subpackage.
//
// db.go, models.go and *.sql.go are generated by `make sqlc`; do not edit.
package store

import (
	"context"
	"database/sql"
	"embed"
	"fmt"
	"log/slog"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/jackc/pgx/v5/stdlib"
	pgxvector "github.com/pgvector/pgvector-go/pgx"
	"github.com/pressly/goose/v3"
)

//go:embed migrations/*.sql
var migrationsFS embed.FS

// DB wraps the pool and the generated query set.
type DB struct {
	Pool *pgxpool.Pool
	*Queries
}

// Connect opens a pool and pings it.
func Connect(ctx context.Context, url string) (*DB, error) {
	cfg, err := pgxpool.ParseConfig(url)
	if err != nil {
		return nil, fmt.Errorf("store: parse url: %w", err)
	}
	cfg.MaxConns = 16
	cfg.MinConns = 2
	cfg.MaxConnLifetime = time.Hour
	cfg.HealthCheckPeriod = 30 * time.Second
	// pgvector's vector type (agent_memory.embedding) on every connection;
	// a database without the extension yet (first boot before 0011) just
	// has no such type, which registration treats as nothing to do.
	cfg.AfterConnect = func(ctx context.Context, conn *pgx.Conn) error {
		if err := pgxvector.RegisterTypes(ctx, conn); err != nil {
			slog.Debug("store: pgvector types not registered", "err", err)
		}
		return nil
	}
	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return nil, fmt.Errorf("store: connect: %w", err)
	}
	pctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	if err := pool.Ping(pctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("store: ping: %w", err)
	}
	return &DB{Pool: pool, Queries: New(pool)}, nil
}

// Close releases the pool.
func (d *DB) Close() { d.Pool.Close() }

// Migrate applies embedded migrations. dir is "up", "down", or "status".
func (d *DB) Migrate(ctx context.Context, dir string) error {
	sqlDB := stdlib.OpenDBFromPool(d.Pool)
	defer sqlDB.Close()
	return migrateDB(ctx, sqlDB, dir)
}

func migrateDB(ctx context.Context, sqlDB *sql.DB, dir string) error {
	goose.SetBaseFS(migrationsFS)
	goose.SetLogger(gooseLogger{})
	if err := goose.SetDialect("postgres"); err != nil {
		return err
	}
	switch dir {
	case "up":
		return goose.UpContext(ctx, sqlDB, "migrations")
	case "down":
		return goose.DownContext(ctx, sqlDB, "migrations")
	case "status":
		return goose.StatusContext(ctx, sqlDB, "migrations")
	}
	return fmt.Errorf("store: unknown migrate direction %q", dir)
}

type gooseLogger struct{}

func (gooseLogger) Fatalf(format string, v ...any) { slog.Error(fmt.Sprintf(format, v...)) }
func (gooseLogger) Printf(format string, v ...any) { slog.Info(fmt.Sprintf(format, v...)) }
