// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gateway.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deleteBudget = `-- name: DeleteBudget :exec
DELETE FROM budgets WHERE id = $1
`

func (q *Queries) DeleteBudget(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBudget, id)
	return err
}

const deleteEndpoint = `-- name: DeleteEndpoint :exec
DELETE FROM endpoints WHERE id = $1
`

func (q *Queries) DeleteEndpoint(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteEndpoint, id)
	return err
}

const deleteProvider = `-- name: DeleteProvider :exec
DELETE FROM providers WHERE id = $1
`

func (q *Queries) DeleteProvider(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteProvider, id)
	return err
}

const deleteRoutingPolicy = `-- name: DeleteRoutingPolicy :exec
DELETE FROM routing_policies WHERE id = $1
`

func (q *Queries) DeleteRoutingPolicy(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoutingPolicy, id)
	return err
}

const deleteRoutingPolicyByName = `-- name: DeleteRoutingPolicyByName :exec
DELETE FROM routing_policies WHERE name = $1
`

func (q *Queries) DeleteRoutingPolicyByName(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteRoutingPolicyByName, name)
	return err
}

const getBudget = `-- name: GetBudget :one
SELECT id, scope, scope_id, period, limit_usd, on_exceed, created_at FROM budgets WHERE scope = $1 AND scope_id IS NOT DISTINCT FROM $2 AND period = $3
`

type GetBudgetParams struct {
	Scope   string        `json:"scope"`
	ScopeID uuid.NullUUID `json:"scope_id"`
	Period  string        `json:"period"`
}

func (q *Queries) GetBudget(ctx context.Context, arg GetBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudget, arg.Scope, arg.ScopeID, arg.Period)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeID,
		&i.Period,
		&i.LimitUsd,
		&i.OnExceed,
		&i.CreatedAt,
	)
	return i, err
}

const getEndpoint = `-- name: GetEndpoint :one
SELECT id, provider_id, model_name, display_name, capabilities, pricing, throughput_class, latency_class, is_local, enabled, health_status, health_checked_at, health_error, p50_latency_ms, error_rate, created_at, updated_at, extra_body FROM endpoints WHERE id = $1
`

func (q *Queries) GetEndpoint(ctx context.Context, id string) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpoint, id)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ModelName,
		&i.DisplayName,
		&i.Capabilities,
		&i.Pricing,
		&i.ThroughputClass,
		&i.LatencyClass,
		&i.IsLocal,
		&i.Enabled,
		&i.HealthStatus,
		&i.HealthCheckedAt,
		&i.HealthError,
		&i.P50LatencyMs,
		&i.ErrorRate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExtraBody,
	)
	return i, err
}

const getRoutingPolicyByName = `-- name: GetRoutingPolicyByName :one
SELECT id, name, yaml, priority, enabled, created_at, updated_at FROM routing_policies WHERE name = $1
`

func (q *Queries) GetRoutingPolicyByName(ctx context.Context, name string) (RoutingPolicy, error) {
	row := q.db.QueryRow(ctx, getRoutingPolicyByName, name)
	var i RoutingPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Yaml,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUsage = `-- name: InsertUsage :one
INSERT INTO usage_ledger (
  user_id, conversation_id, agent_id, agent_run_id, api_key_id, endpoint_id, model, task_class, policy_name, decision,
  input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, cost_usd, latency_ms, ttft_ms, finish_reason, error,
  session_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)
RETURNING id
`

type InsertUsageParams struct {
	UserID           uuid.NullUUID   `json:"user_id"`
	ConversationID   uuid.NullUUID   `json:"conversation_id"`
	AgentID          uuid.NullUUID   `json:"agent_id"`
	AgentRunID       uuid.NullUUID   `json:"agent_run_id"`
	ApiKeyID         uuid.NullUUID   `json:"api_key_id"`
	EndpointID       *string         `json:"endpoint_id"`
	Model            *string         `json:"model"`
	TaskClass        *string         `json:"task_class"`
	PolicyName       *string         `json:"policy_name"`
	Decision         json.RawMessage `json:"decision"`
	InputTokens      int32           `json:"input_tokens"`
	OutputTokens     int32           `json:"output_tokens"`
	CacheReadTokens  int32           `json:"cache_read_tokens"`
	CacheWriteTokens int32           `json:"cache_write_tokens"`
	CostUsd          float64         `json:"cost_usd"`
	LatencyMs        *int32          `json:"latency_ms"`
	TtftMs           *int32          `json:"ttft_ms"`
	FinishReason     *string         `json:"finish_reason"`
	Error            *string         `json:"error"`
	SessionID        *string         `json:"session_id"`
}

func (q *Queries) InsertUsage(ctx context.Context, arg InsertUsageParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertUsage,
		arg.UserID,
		arg.ConversationID,
		arg.AgentID,
		arg.AgentRunID,
		arg.ApiKeyID,
		arg.EndpointID,
		arg.Model,
		arg.TaskClass,
		arg.PolicyName,
		arg.Decision,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.CacheWriteTokens,
		arg.CostUsd,
		arg.LatencyMs,
		arg.TtftMs,
		arg.FinishReason,
		arg.Error,
		arg.SessionID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAllBudgets = `-- name: ListAllBudgets :many
SELECT id, scope, scope_id, period, limit_usd, on_exceed, created_at FROM budgets ORDER BY scope, period
`

func (q *Queries) ListAllBudgets(ctx context.Context) ([]Budget, error) {
	rows, err := q.db.Query(ctx, listAllBudgets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Budget{}
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ScopeID,
			&i.Period,
			&i.LimitUsd,
			&i.OnExceed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllRoutingPolicies = `-- name: ListAllRoutingPolicies :many
SELECT id, name, yaml, priority, enabled, created_at, updated_at FROM routing_policies ORDER BY priority, name
`

func (q *Queries) ListAllRoutingPolicies(ctx context.Context) ([]RoutingPolicy, error) {
	rows, err := q.db.Query(ctx, listAllRoutingPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoutingPolicy{}
	for rows.Next() {
		var i RoutingPolicy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Yaml,
			&i.Priority,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetsForScope = `-- name: ListBudgetsForScope :many
SELECT id, scope, scope_id, period, limit_usd, on_exceed, created_at FROM budgets WHERE scope = $1 AND scope_id IS NOT DISTINCT FROM $2
`

type ListBudgetsForScopeParams struct {
	Scope   string        `json:"scope"`
	ScopeID uuid.NullUUID `json:"scope_id"`
}

func (q *Queries) ListBudgetsForScope(ctx context.Context, arg ListBudgetsForScopeParams) ([]Budget, error) {
	rows, err := q.db.Query(ctx, listBudgetsForScope, arg.Scope, arg.ScopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Budget{}
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ScopeID,
			&i.Period,
			&i.LimitUsd,
			&i.OnExceed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndpoints = `-- name: ListEndpoints :many
SELECT id, provider_id, model_name, display_name, capabilities, pricing, throughput_class, latency_class, is_local, enabled, health_status, health_checked_at, health_error, p50_latency_ms, error_rate, created_at, updated_at, extra_body FROM endpoints ORDER BY id
`

func (q *Queries) ListEndpoints(ctx context.Context) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, listEndpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Endpoint{}
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ModelName,
			&i.DisplayName,
			&i.Capabilities,
			&i.Pricing,
			&i.ThroughputClass,
			&i.LatencyClass,
			&i.IsLocal,
			&i.Enabled,
			&i.HealthStatus,
			&i.HealthCheckedAt,
			&i.HealthError,
			&i.P50LatencyMs,
			&i.ErrorRate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExtraBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviders = `-- name: ListProviders :many
SELECT id, kind, name, base_url, api_key_env, headers, created_at, updated_at FROM providers ORDER BY id
`

func (q *Queries) ListProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.BaseUrl,
			&i.ApiKeyEnv,
			&i.Headers,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutingPolicies = `-- name: ListRoutingPolicies :many
SELECT id, name, yaml, priority, enabled, created_at, updated_at FROM routing_policies WHERE enabled ORDER BY priority, name
`

func (q *Queries) ListRoutingPolicies(ctx context.Context) ([]RoutingPolicy, error) {
	rows, err := q.db.Query(ctx, listRoutingPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoutingPolicy{}
	for rows.Next() {
		var i RoutingPolicy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Yaml,
			&i.Priority,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageAll = `-- name: ListUsageAll :many
SELECT id, created_at, user_id, conversation_id, agent_id, agent_run_id, api_key_id, endpoint_id, model, task_class, policy_name, decision, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, cost_usd, latency_ms, ttft_ms, finish_reason, error, session_id FROM usage_ledger ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListUsageAllParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsageAll(ctx context.Context, arg ListUsageAllParams) ([]UsageLedger, error) {
	rows, err := q.db.Query(ctx, listUsageAll, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageLedger{}
	for rows.Next() {
		var i UsageLedger
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.ConversationID,
			&i.AgentID,
			&i.AgentRunID,
			&i.ApiKeyID,
			&i.EndpointID,
			&i.Model,
			&i.TaskClass,
			&i.PolicyName,
			&i.Decision,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.CostUsd,
			&i.LatencyMs,
			&i.TtftMs,
			&i.FinishReason,
			&i.Error,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageForUser = `-- name: ListUsageForUser :many
SELECT id, created_at, user_id, conversation_id, agent_id, agent_run_id, api_key_id, endpoint_id, model, task_class, policy_name, decision, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, cost_usd, latency_ms, ttft_ms, finish_reason, error, session_id FROM usage_ledger WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListUsageForUserParams struct {
	UserID uuid.NullUUID `json:"user_id"`
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
}

func (q *Queries) ListUsageForUser(ctx context.Context, arg ListUsageForUserParams) ([]UsageLedger, error) {
	rows, err := q.db.Query(ctx, listUsageForUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageLedger{}
	for rows.Next() {
		var i UsageLedger
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.ConversationID,
			&i.AgentID,
			&i.AgentRunID,
			&i.ApiKeyID,
			&i.EndpointID,
			&i.Model,
			&i.TaskClass,
			&i.PolicyName,
			&i.Decision,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.CostUsd,
			&i.LatencyMs,
			&i.TtftMs,
			&i.FinishReason,
			&i.Error,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEndpointEnabled = `-- name: SetEndpointEnabled :exec
UPDATE endpoints SET enabled = $2 WHERE id = $1
`

type SetEndpointEnabledParams struct {
	ID      string `json:"id"`
	Enabled bool   `json:"enabled"`
}

func (q *Queries) SetEndpointEnabled(ctx context.Context, arg SetEndpointEnabledParams) error {
	_, err := q.db.Exec(ctx, setEndpointEnabled, arg.ID, arg.Enabled)
	return err
}

const sumUsageForAPIKeySince = `-- name: SumUsageForAPIKeySince :one
SELECT COALESCE(SUM(cost_usd), 0)::numeric AS cost_usd FROM usage_ledger WHERE api_key_id = $1 AND created_at >= $2
`

type SumUsageForAPIKeySinceParams struct {
	ApiKeyID  uuid.NullUUID `json:"api_key_id"`
	CreatedAt time.Time     `json:"created_at"`
}

func (q *Queries) SumUsageForAPIKeySince(ctx context.Context, arg SumUsageForAPIKeySinceParams) (float64, error) {
	row := q.db.QueryRow(ctx, sumUsageForAPIKeySince, arg.ApiKeyID, arg.CreatedAt)
	var cost_usd float64
	err := row.Scan(&cost_usd)
	return cost_usd, err
}

const sumUsageForAgentSince = `-- name: SumUsageForAgentSince :one
SELECT COALESCE(SUM(cost_usd), 0)::numeric AS cost_usd FROM usage_ledger WHERE agent_id = $1 AND created_at >= $2
`

type SumUsageForAgentSinceParams struct {
	AgentID   uuid.NullUUID `json:"agent_id"`
	CreatedAt time.Time     `json:"created_at"`
}

func (q *Queries) SumUsageForAgentSince(ctx context.Context, arg SumUsageForAgentSinceParams) (float64, error) {
	row := q.db.QueryRow(ctx, sumUsageForAgentSince, arg.AgentID, arg.CreatedAt)
	var cost_usd float64
	err := row.Scan(&cost_usd)
	return cost_usd, err
}

const sumUsageForUserSince = `-- name: SumUsageForUserSince :one
SELECT COALESCE(SUM(cost_usd), 0)::numeric AS cost_usd FROM usage_ledger WHERE user_id = $1 AND created_at >= $2
`

type SumUsageForUserSinceParams struct {
	UserID    uuid.NullUUID `json:"user_id"`
	CreatedAt time.Time     `json:"created_at"`
}

func (q *Queries) SumUsageForUserSince(ctx context.Context, arg SumUsageForUserSinceParams) (float64, error) {
	row := q.db.QueryRow(ctx, sumUsageForUserSince, arg.UserID, arg.CreatedAt)
	var cost_usd float64
	err := row.Scan(&cost_usd)
	return cost_usd, err
}

const sumUsageSince = `-- name: SumUsageSince :one
SELECT COALESCE(SUM(cost_usd), 0)::numeric AS cost_usd FROM usage_ledger WHERE created_at >= $1
`

func (q *Queries) SumUsageSince(ctx context.Context, createdAt time.Time) (float64, error) {
	row := q.db.QueryRow(ctx, sumUsageSince, createdAt)
	var cost_usd float64
	err := row.Scan(&cost_usd)
	return cost_usd, err
}

const updateEndpointHealth = `-- name: UpdateEndpointHealth :exec
UPDATE endpoints SET health_status = $2, health_checked_at = now(), health_error = $3, p50_latency_ms = $4, error_rate = $5
WHERE id = $1
`

type UpdateEndpointHealthParams struct {
	ID           string   `json:"id"`
	HealthStatus string   `json:"health_status"`
	HealthError  *string  `json:"health_error"`
	P50LatencyMs *int32   `json:"p50_latency_ms"`
	ErrorRate    *float32 `json:"error_rate"`
}

func (q *Queries) UpdateEndpointHealth(ctx context.Context, arg UpdateEndpointHealthParams) error {
	_, err := q.db.Exec(ctx, updateEndpointHealth,
		arg.ID,
		arg.HealthStatus,
		arg.HealthError,
		arg.P50LatencyMs,
		arg.ErrorRate,
	)
	return err
}

const upsertBudget = `-- name: UpsertBudget :one
INSERT INTO budgets (scope, scope_id, period, limit_usd, on_exceed) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (scope, scope_id, period) DO UPDATE SET limit_usd = EXCLUDED.limit_usd, on_exceed = EXCLUDED.on_exceed
RETURNING id, scope, scope_id, period, limit_usd, on_exceed, created_at
`

type UpsertBudgetParams struct {
	Scope    string        `json:"scope"`
	ScopeID  uuid.NullUUID `json:"scope_id"`
	Period   string        `json:"period"`
	LimitUsd float64       `json:"limit_usd"`
	OnExceed string        `json:"on_exceed"`
}

func (q *Queries) UpsertBudget(ctx context.Context, arg UpsertBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, upsertBudget,
		arg.Scope,
		arg.ScopeID,
		arg.Period,
		arg.LimitUsd,
		arg.OnExceed,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeID,
		&i.Period,
		&i.LimitUsd,
		&i.OnExceed,
		&i.CreatedAt,
	)
	return i, err
}

const upsertEndpoint = `-- name: UpsertEndpoint :exec
INSERT INTO endpoints (id, provider_id, model_name, display_name, capabilities, pricing, throughput_class, latency_class, is_local, enabled, extra_body)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO UPDATE SET
  provider_id = EXCLUDED.provider_id, model_name = EXCLUDED.model_name, display_name = EXCLUDED.display_name,
  capabilities = EXCLUDED.capabilities, pricing = EXCLUDED.pricing,
  throughput_class = EXCLUDED.throughput_class, latency_class = EXCLUDED.latency_class,
  is_local = EXCLUDED.is_local, extra_body = EXCLUDED.extra_body
`

type UpsertEndpointParams struct {
	ID              string          `json:"id"`
	ProviderID      string          `json:"provider_id"`
	ModelName       string          `json:"model_name"`
	DisplayName     string          `json:"display_name"`
	Capabilities    json.RawMessage `json:"capabilities"`
	Pricing         json.RawMessage `json:"pricing"`
	ThroughputClass string          `json:"throughput_class"`
	LatencyClass    string          `json:"latency_class"`
	IsLocal         bool            `json:"is_local"`
	Enabled         bool            `json:"enabled"`
	ExtraBody       json.RawMessage `json:"extra_body"`
}

func (q *Queries) UpsertEndpoint(ctx context.Context, arg UpsertEndpointParams) error {
	_, err := q.db.Exec(ctx, upsertEndpoint,
		arg.ID,
		arg.ProviderID,
		arg.ModelName,
		arg.DisplayName,
		arg.Capabilities,
		arg.Pricing,
		arg.ThroughputClass,
		arg.LatencyClass,
		arg.IsLocal,
		arg.Enabled,
		arg.ExtraBody,
	)
	return err
}

const upsertProvider = `-- name: UpsertProvider :exec
INSERT INTO providers (id, kind, name, base_url, api_key_env, headers)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET
  kind = EXCLUDED.kind, name = EXCLUDED.name, base_url = EXCLUDED.base_url,
  api_key_env = EXCLUDED.api_key_env, headers = EXCLUDED.headers
`

type UpsertProviderParams struct {
	ID        string          `json:"id"`
	Kind      string          `json:"kind"`
	Name      string          `json:"name"`
	BaseUrl   string          `json:"base_url"`
	ApiKeyEnv *string         `json:"api_key_env"`
	Headers   json.RawMessage `json:"headers"`
}

func (q *Queries) UpsertProvider(ctx context.Context, arg UpsertProviderParams) error {
	_, err := q.db.Exec(ctx, upsertProvider,
		arg.ID,
		arg.Kind,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKeyEnv,
		arg.Headers,
	)
	return err
}

const upsertRoutingPolicy = `-- name: UpsertRoutingPolicy :one
INSERT INTO routing_policies (name, yaml, priority, enabled) VALUES ($1, $2, $3, $4)
ON CONFLICT (name) DO UPDATE SET yaml = EXCLUDED.yaml, priority = EXCLUDED.priority, enabled = EXCLUDED.enabled
RETURNING id, name, yaml, priority, enabled, created_at, updated_at
`

type UpsertRoutingPolicyParams struct {
	Name     string `json:"name"`
	Yaml     string `json:"yaml"`
	Priority int32  `json:"priority"`
	Enabled  bool   `json:"enabled"`
}

func (q *Queries) UpsertRoutingPolicy(ctx context.Context, arg UpsertRoutingPolicyParams) (RoutingPolicy, error) {
	row := q.db.QueryRow(ctx, upsertRoutingPolicy,
		arg.Name,
		arg.Yaml,
		arg.Priority,
		arg.Enabled,
	)
	var i RoutingPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Yaml,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const usageByEndpointSince = `-- name: UsageByEndpointSince :many
SELECT endpoint_id, count(*) AS calls,
       SUM(input_tokens)::bigint AS input_tokens, SUM(output_tokens)::bigint AS output_tokens,
       SUM(cost_usd)::numeric AS cost_usd, AVG(latency_ms)::int AS avg_latency_ms
FROM usage_ledger WHERE created_at >= $1 GROUP BY endpoint_id ORDER BY cost_usd DESC
`

type UsageByEndpointSinceRow struct {
	EndpointID   *string `json:"endpoint_id"`
	Calls        int64   `json:"calls"`
	InputTokens  int64   `json:"input_tokens"`
	OutputTokens int64   `json:"output_tokens"`
	CostUsd      float64 `json:"cost_usd"`
	AvgLatencyMs int32   `json:"avg_latency_ms"`
}

func (q *Queries) UsageByEndpointSince(ctx context.Context, createdAt time.Time) ([]UsageByEndpointSinceRow, error) {
	rows, err := q.db.Query(ctx, usageByEndpointSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageByEndpointSinceRow{}
	for rows.Next() {
		var i UsageByEndpointSinceRow
		if err := rows.Scan(
			&i.EndpointID,
			&i.Calls,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostUsd,
			&i.AvgLatencyMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usageByUserSince = `-- name: UsageByUserSince :many
SELECT user_id, count(*) AS calls, SUM(cost_usd)::numeric AS cost_usd
FROM usage_ledger WHERE created_at >= $1 GROUP BY user_id ORDER BY cost_usd DESC
`

type UsageByUserSinceRow struct {
	UserID  uuid.NullUUID `json:"user_id"`
	Calls   int64         `json:"calls"`
	CostUsd float64       `json:"cost_usd"`
}

func (q *Queries) UsageByUserSince(ctx context.Context, createdAt time.Time) ([]UsageByUserSinceRow, error) {
	rows, err := q.db.Query(ctx, usageByUserSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageByUserSinceRow{}
	for rows.Next() {
		var i UsageByUserSinceRow
		if err := rows.Scan(&i.UserID, &i.Calls, &i.CostUsd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
