// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const attachmentMediaProjects = `-- name: AttachmentMediaProjects :many
SELECT project_id FROM media_jobs WHERE $1::uuid = ANY(output_attachment_ids)
`

func (q *Queries) AttachmentMediaProjects(ctx context.Context, dollar_1 uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, attachmentMediaProjects, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var project_id uuid.UUID
		if err := rows.Scan(&project_id); err != nil {
			return nil, err
		}
		items = append(items, project_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cancelMediaJob = `-- name: CancelMediaJob :one
UPDATE media_jobs SET status = 'cancelled', ended_at = now() WHERE id = $1 AND status = 'queued' RETURNING id, user_id, project_id, conversation_id, kind, selector, endpoint_id, inputs, provider_job_id, status, progress, output_attachment_ids, cost_usd, error, created_at, started_at, ended_at, updated_at
`

func (q *Queries) CancelMediaJob(ctx context.Context, id uuid.UUID) (MediaJob, error) {
	row := q.db.QueryRow(ctx, cancelMediaJob, id)
	var i MediaJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.ConversationID,
		&i.Kind,
		&i.Selector,
		&i.EndpointID,
		&i.Inputs,
		&i.ProviderJobID,
		&i.Status,
		&i.Progress,
		&i.OutputAttachmentIds,
		&i.CostUsd,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimMediaJob = `-- name: ClaimMediaJob :one
UPDATE media_jobs SET status = 'running', started_at = now(), progress = 0, error = NULL
WHERE id = $1 AND status = 'queued' RETURNING id, user_id, project_id, conversation_id, kind, selector, endpoint_id, inputs, provider_job_id, status, progress, output_attachment_ids, cost_usd, error, created_at, started_at, ended_at, updated_at
`

func (q *Queries) ClaimMediaJob(ctx context.Context, id uuid.UUID) (MediaJob, error) {
	row := q.db.QueryRow(ctx, claimMediaJob, id)
	var i MediaJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.ConversationID,
		&i.Kind,
		&i.Selector,
		&i.EndpointID,
		&i.Inputs,
		&i.ProviderJobID,
		&i.Status,
		&i.Progress,
		&i.OutputAttachmentIds,
		&i.CostUsd,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMediaJob = `-- name: CreateMediaJob :one
INSERT INTO media_jobs (user_id, project_id, conversation_id, kind, selector, inputs)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, user_id, project_id, conversation_id, kind, selector, endpoint_id, inputs, provider_job_id, status, progress, output_attachment_ids, cost_usd, error, created_at, started_at, ended_at, updated_at
`

type CreateMediaJobParams struct {
	UserID         uuid.UUID       `json:"user_id"`
	ProjectID      uuid.UUID       `json:"project_id"`
	ConversationID uuid.NullUUID   `json:"conversation_id"`
	Kind           string          `json:"kind"`
	Selector       string          `json:"selector"`
	Inputs         json.RawMessage `json:"inputs"`
}

func (q *Queries) CreateMediaJob(ctx context.Context, arg CreateMediaJobParams) (MediaJob, error) {
	row := q.db.QueryRow(ctx, createMediaJob,
		arg.UserID,
		arg.ProjectID,
		arg.ConversationID,
		arg.Kind,
		arg.Selector,
		arg.Inputs,
	)
	var i MediaJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.ConversationID,
		&i.Kind,
		&i.Selector,
		&i.EndpointID,
		&i.Inputs,
		&i.ProviderJobID,
		&i.Status,
		&i.Progress,
		&i.OutputAttachmentIds,
		&i.CostUsd,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMediaJob = `-- name: DeleteMediaJob :exec
DELETE FROM media_jobs WHERE id = $1 AND status IN ('done','failed','cancelled')
`

func (q *Queries) DeleteMediaJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMediaJob, id)
	return err
}

const failMediaJob = `-- name: FailMediaJob :exec
UPDATE media_jobs SET status = 'failed', endpoint_id = COALESCE($3, endpoint_id), error = $2, ended_at = now()
WHERE id = $1
`

type FailMediaJobParams struct {
	ID         uuid.UUID `json:"id"`
	Error      *string   `json:"error"`
	EndpointID *string   `json:"endpoint_id"`
}

func (q *Queries) FailMediaJob(ctx context.Context, arg FailMediaJobParams) error {
	_, err := q.db.Exec(ctx, failMediaJob, arg.ID, arg.Error, arg.EndpointID)
	return err
}

const finishMediaJob = `-- name: FinishMediaJob :exec
UPDATE media_jobs SET status = 'done', progress = 1, endpoint_id = $2, output_attachment_ids = $3, cost_usd = $4, ended_at = now()
WHERE id = $1
`

type FinishMediaJobParams struct {
	ID                  uuid.UUID   `json:"id"`
	EndpointID          *string     `json:"endpoint_id"`
	OutputAttachmentIds []uuid.UUID `json:"output_attachment_ids"`
	CostUsd             float64     `json:"cost_usd"`
}

func (q *Queries) FinishMediaJob(ctx context.Context, arg FinishMediaJobParams) error {
	_, err := q.db.Exec(ctx, finishMediaJob,
		arg.ID,
		arg.EndpointID,
		arg.OutputAttachmentIds,
		arg.CostUsd,
	)
	return err
}

const getMediaJob = `-- name: GetMediaJob :one
SELECT id, user_id, project_id, conversation_id, kind, selector, endpoint_id, inputs, provider_job_id, status, progress, output_attachment_ids, cost_usd, error, created_at, started_at, ended_at, updated_at FROM media_jobs WHERE id = $1
`

func (q *Queries) GetMediaJob(ctx context.Context, id uuid.UUID) (MediaJob, error) {
	row := q.db.QueryRow(ctx, getMediaJob, id)
	var i MediaJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.ConversationID,
		&i.Kind,
		&i.Selector,
		&i.EndpointID,
		&i.Inputs,
		&i.ProviderJobID,
		&i.Status,
		&i.Progress,
		&i.OutputAttachmentIds,
		&i.CostUsd,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAttachmentsByIDs = `-- name: ListAttachmentsByIDs :many
SELECT id, user_id, blob_key, mime, bytes, sha256, filename, width, height, created_at FROM attachments WHERE id = ANY($1::uuid[])
`

func (q *Queries) ListAttachmentsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BlobKey,
			&i.Mime,
			&i.Bytes,
			&i.Sha256,
			&i.Filename,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaJobsForProject = `-- name: ListMediaJobsForProject :many
SELECT id, user_id, project_id, conversation_id, kind, selector, endpoint_id, inputs, provider_job_id, status, progress, output_attachment_ids, cost_usd, error, created_at, started_at, ended_at, updated_at FROM media_jobs WHERE project_id = $1 AND ($4::text IS NULL OR kind = $4::text)
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListMediaJobsForProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
	Kind      *string   `json:"kind"`
}

func (q *Queries) ListMediaJobsForProject(ctx context.Context, arg ListMediaJobsForProjectParams) ([]MediaJob, error) {
	rows, err := q.db.Query(ctx, listMediaJobsForProject,
		arg.ProjectID,
		arg.Limit,
		arg.Offset,
		arg.Kind,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaJob{}
	for rows.Next() {
		var i MediaJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.ConversationID,
			&i.Kind,
			&i.Selector,
			&i.EndpointID,
			&i.Inputs,
			&i.ProviderJobID,
			&i.Status,
			&i.Progress,
			&i.OutputAttachmentIds,
			&i.CostUsd,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMediaJobProgress = `-- name: SetMediaJobProgress :exec
UPDATE media_jobs SET progress = $2, provider_job_id = COALESCE($3, provider_job_id)
WHERE id = $1 AND status = 'running'
`

type SetMediaJobProgressParams struct {
	ID            uuid.UUID `json:"id"`
	Progress      float32   `json:"progress"`
	ProviderJobID *string   `json:"provider_job_id"`
}

func (q *Queries) SetMediaJobProgress(ctx context.Context, arg SetMediaJobProgressParams) error {
	_, err := q.db.Exec(ctx, setMediaJobProgress, arg.ID, arg.Progress, arg.ProviderJobID)
	return err
}
