// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memory.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/pgvector/pgvector-go"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const countMemoriesForAgent = `-- name: CountMemoriesForAgent :one
SELECT count(*) FROM agent_memory WHERE agent_id = $1
`

func (q *Queries) CountMemoriesForAgent(ctx context.Context, agentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMemoriesForAgent, agentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMemoriesForAgent = `-- name: DeleteMemoriesForAgent :exec
DELETE FROM agent_memory WHERE agent_id = $1
`

func (q *Queries) DeleteMemoriesForAgent(ctx context.Context, agentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMemoriesForAgent, agentID)
	return err
}

const deleteMemory = `-- name: DeleteMemory :exec
DELETE FROM agent_memory WHERE id = $1 AND agent_id = $2
`

type DeleteMemoryParams struct {
	ID      uuid.UUID `json:"id"`
	AgentID uuid.UUID `json:"agent_id"`
}

func (q *Queries) DeleteMemory(ctx context.Context, arg DeleteMemoryParams) error {
	_, err := q.db.Exec(ctx, deleteMemory, arg.ID, arg.AgentID)
	return err
}

const listMemoriesForAgent = `-- name: ListMemoriesForAgent :many
SELECT id, agent_id, kind, content, content_hash, embedding, source_run_id, importance, last_used_at, created_at FROM agent_memory WHERE agent_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListMemoriesForAgentParams struct {
	AgentID uuid.UUID `json:"agent_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListMemoriesForAgent(ctx context.Context, arg ListMemoriesForAgentParams) ([]AgentMemory, error) {
	rows, err := q.db.Query(ctx, listMemoriesForAgent, arg.AgentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMemory{}
	for rows.Next() {
		var i AgentMemory
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Kind,
			&i.Content,
			&i.ContentHash,
			&i.Embedding,
			&i.SourceRunID,
			&i.Importance,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMemories = `-- name: SearchMemories :many
SELECT id, agent_id, kind, content, content_hash, embedding, source_run_id, importance, last_used_at, created_at, (embedding <=> $2::vector)::float8 AS distance FROM agent_memory
WHERE agent_id = $1 AND embedding IS NOT NULL
ORDER BY embedding <=> $2::vector LIMIT $3
`

type SearchMemoriesParams struct {
	AgentID uuid.UUID          `json:"agent_id"`
	Column2 pgvector_go.Vector `json:"column_2"`
	Limit   int32              `json:"limit"`
}

type SearchMemoriesRow struct {
	ID          uuid.UUID        `json:"id"`
	AgentID     uuid.UUID        `json:"agent_id"`
	Kind        string           `json:"kind"`
	Content     string           `json:"content"`
	ContentHash []byte           `json:"content_hash"`
	Embedding   *pgvector.Vector `json:"embedding"`
	SourceRunID uuid.NullUUID    `json:"source_run_id"`
	Importance  float32          `json:"importance"`
	LastUsedAt  *time.Time       `json:"last_used_at"`
	CreatedAt   time.Time        `json:"created_at"`
	Distance    float64          `json:"distance"`
}

func (q *Queries) SearchMemories(ctx context.Context, arg SearchMemoriesParams) ([]SearchMemoriesRow, error) {
	rows, err := q.db.Query(ctx, searchMemories, arg.AgentID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMemoriesRow{}
	for rows.Next() {
		var i SearchMemoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Kind,
			&i.Content,
			&i.ContentHash,
			&i.Embedding,
			&i.SourceRunID,
			&i.Importance,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topMemoriesByImportance = `-- name: TopMemoriesByImportance :many
SELECT id, agent_id, kind, content, content_hash, embedding, source_run_id, importance, last_used_at, created_at FROM agent_memory WHERE agent_id = $1 ORDER BY importance DESC, created_at DESC LIMIT $2
`

type TopMemoriesByImportanceParams struct {
	AgentID uuid.UUID `json:"agent_id"`
	Limit   int32     `json:"limit"`
}

func (q *Queries) TopMemoriesByImportance(ctx context.Context, arg TopMemoriesByImportanceParams) ([]AgentMemory, error) {
	rows, err := q.db.Query(ctx, topMemoriesByImportance, arg.AgentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMemory{}
	for rows.Next() {
		var i AgentMemory
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Kind,
			&i.Content,
			&i.ContentHash,
			&i.Embedding,
			&i.SourceRunID,
			&i.Importance,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchMemories = `-- name: TouchMemories :exec
UPDATE agent_memory SET last_used_at = now() WHERE id = ANY($1::uuid[])
`

func (q *Queries) TouchMemories(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchMemories, dollar_1)
	return err
}

const upsertMemory = `-- name: UpsertMemory :one
INSERT INTO agent_memory (agent_id, kind, content, content_hash, embedding, source_run_id, importance)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (agent_id, content_hash) DO UPDATE SET
  importance = GREATEST(agent_memory.importance, EXCLUDED.importance),
  embedding = COALESCE(EXCLUDED.embedding, agent_memory.embedding),
  source_run_id = COALESCE(EXCLUDED.source_run_id, agent_memory.source_run_id)
RETURNING id, agent_id, kind, content, content_hash, embedding, source_run_id, importance, last_used_at, created_at
`

type UpsertMemoryParams struct {
	AgentID     uuid.UUID        `json:"agent_id"`
	Kind        string           `json:"kind"`
	Content     string           `json:"content"`
	ContentHash []byte           `json:"content_hash"`
	Embedding   *pgvector.Vector `json:"embedding"`
	SourceRunID uuid.NullUUID    `json:"source_run_id"`
	Importance  float32          `json:"importance"`
}

func (q *Queries) UpsertMemory(ctx context.Context, arg UpsertMemoryParams) (AgentMemory, error) {
	row := q.db.QueryRow(ctx, upsertMemory,
		arg.AgentID,
		arg.Kind,
		arg.Content,
		arg.ContentHash,
		arg.Embedding,
		arg.SourceRunID,
		arg.Importance,
	)
	var i AgentMemory
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Kind,
		&i.Content,
		&i.ContentHash,
		&i.Embedding,
		&i.SourceRunID,
		&i.Importance,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}
