// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/pgvector/pgvector-go"
)

type Adapter struct {
	ID             uuid.UUID       `json:"id"`
	Name           string          `json:"name"`
	BaseModel      string          `json:"base_model"`
	BaseEndpointID *string         `json:"base_endpoint_id"`
	FinetuneJobID  uuid.NullUUID   `json:"finetune_job_id"`
	BlobKey        string          `json:"blob_key"`
	Bytes          int64           `json:"bytes"`
	EvalScore      *float32        `json:"eval_score"`
	BaselineScore  *float32        `json:"baseline_score"`
	Eval           json.RawMessage `json:"eval"`
	Promoted       bool            `json:"promoted"`
	EndpointID     *string         `json:"endpoint_id"`
	CreatedAt      time.Time       `json:"created_at"`
	EvaluatedAt    *time.Time      `json:"evaluated_at"`
}

type Agent struct {
	ID            uuid.UUID       `json:"id"`
	OwnerID       uuid.UUID       `json:"owner_id"`
	Name          string          `json:"name"`
	Goal          string          `json:"goal"`
	SystemPrompt  string          `json:"system_prompt"`
	ModelPolicy   json.RawMessage `json:"model_policy"`
	ToolAllowlist []string        `json:"tool_allowlist"`
	ToolPolicies  json.RawMessage `json:"tool_policies"`
	McpServers    json.RawMessage `json:"mcp_servers"`
	MemoryConfig  json.RawMessage `json:"memory_config"`
	MaxSteps      int32           `json:"max_steps"`
	Enabled       bool            `json:"enabled"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
	ProjectID     uuid.NullUUID   `json:"project_id"`
	LastRunAt     *time.Time      `json:"last_run_at"`
}

type AgentMemory struct {
	ID          uuid.UUID        `json:"id"`
	AgentID     uuid.UUID        `json:"agent_id"`
	Kind        string           `json:"kind"`
	Content     string           `json:"content"`
	ContentHash []byte           `json:"content_hash"`
	Embedding   *pgvector.Vector `json:"embedding"`
	SourceRunID uuid.NullUUID    `json:"source_run_id"`
	Importance  float32          `json:"importance"`
	LastUsedAt  *time.Time       `json:"last_used_at"`
	CreatedAt   time.Time        `json:"created_at"`
}

type AgentRun struct {
	ID             uuid.UUID       `json:"id"`
	AgentID        uuid.NullUUID   `json:"agent_id"`
	ConversationID uuid.UUID       `json:"conversation_id"`
	UserID         uuid.NullUUID   `json:"user_id"`
	TriggerID      uuid.NullUUID   `json:"trigger_id"`
	Status         string          `json:"status"`
	Request        json.RawMessage `json:"request"`
	ToolPolicies   json.RawMessage `json:"tool_policies"`
	MaxSteps       int32           `json:"max_steps"`
	StepCount      int32           `json:"step_count"`
	FirstMessageID uuid.NullUUID   `json:"first_message_id"`
	CostUsd        float64         `json:"cost_usd"`
	Error          *string         `json:"error"`
	HeartbeatAt    time.Time       `json:"heartbeat_at"`
	OwnerPid       *string         `json:"owner_pid"`
	StartedAt      *time.Time      `json:"started_at"`
	EndedAt        *time.Time      `json:"ended_at"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type AgentStep struct {
	ID         uuid.UUID       `json:"id"`
	RunID      uuid.UUID       `json:"run_id"`
	Seq        int32           `json:"seq"`
	Kind       string          `json:"kind"`
	Input      json.RawMessage `json:"input"`
	Output     json.RawMessage `json:"output"`
	Checkpoint json.RawMessage `json:"checkpoint"`
	Usage      json.RawMessage `json:"usage"`
	Error      *string         `json:"error"`
	StartedAt  time.Time       `json:"started_at"`
	EndedAt    *time.Time      `json:"ended_at"`
}

type AgentTrigger struct {
	ID         uuid.UUID       `json:"id"`
	AgentID    uuid.UUID       `json:"agent_id"`
	Kind       string          `json:"kind"`
	Spec       json.RawMessage `json:"spec"`
	SecretHash []byte          `json:"secret_hash"`
	Enabled    bool            `json:"enabled"`
	CreatedAt  time.Time       `json:"created_at"`
	Name       string          `json:"name"`
	NextRunAt  *time.Time      `json:"next_run_at"`
	LastRunAt  *time.Time      `json:"last_run_at"`
	LastError  *string         `json:"last_error"`
}

type ApiKey struct {
	ID            uuid.UUID     `json:"id"`
	UserID        uuid.UUID     `json:"user_id"`
	Name          string        `json:"name"`
	Prefix        string        `json:"prefix"`
	KeyHash       []byte        `json:"key_hash"`
	Scopes        []string      `json:"scopes"`
	DefaultPolicy string        `json:"default_policy"`
	BudgetID      uuid.NullUUID `json:"budget_id"`
	CreatedAt     time.Time     `json:"created_at"`
	LastUsedAt    *time.Time    `json:"last_used_at"`
	RevokedAt     *time.Time    `json:"revoked_at"`
}

type Approval struct {
	ID         uuid.UUID       `json:"id"`
	RunID      uuid.UUID       `json:"run_id"`
	StepSeq    int32           `json:"step_seq"`
	ToolCallID string          `json:"tool_call_id"`
	ToolName   string          `json:"tool_name"`
	Args       json.RawMessage `json:"args"`
	Status     string          `json:"status"`
	DecidedBy  uuid.NullUUID   `json:"decided_by"`
	DecidedAt  *time.Time      `json:"decided_at"`
	Note       *string         `json:"note"`
	CreatedAt  time.Time       `json:"created_at"`
}

type Artifact struct {
	ID             uuid.UUID `json:"id"`
	ConversationID uuid.UUID `json:"conversation_id"`
	Kind           string    `json:"kind"`
	Title          string    `json:"title"`
	Language       *string   `json:"language"`
	CurrentVersion int32     `json:"current_version"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type ArtifactVersion struct {
	ID                 uuid.UUID       `json:"id"`
	ArtifactID         uuid.UUID       `json:"artifact_id"`
	Version            int32           `json:"version"`
	Content            *string         `json:"content"`
	BlobKey            *string         `json:"blob_key"`
	DesignContext      json.RawMessage `json:"design_context"`
	CreatedByMessageID uuid.NullUUID   `json:"created_by_message_id"`
	CreatedAt          time.Time       `json:"created_at"`
}

type Attachment struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	BlobKey   string    `json:"blob_key"`
	Mime      string    `json:"mime"`
	Bytes     int64     `json:"bytes"`
	Sha256    []byte    `json:"sha256"`
	Filename  string    `json:"filename"`
	Width     *int32    `json:"width"`
	Height    *int32    `json:"height"`
	CreatedAt time.Time `json:"created_at"`
}

type Budget struct {
	ID        uuid.UUID     `json:"id"`
	Scope     string        `json:"scope"`
	ScopeID   uuid.NullUUID `json:"scope_id"`
	Period    string        `json:"period"`
	LimitUsd  float64       `json:"limit_usd"`
	OnExceed  string        `json:"on_exceed"`
	CreatedAt time.Time     `json:"created_at"`
}

type CcJob struct {
	ID        string        `json:"id"`
	UserID    uuid.NullUUID `json:"user_id"`
	Target    string        `json:"target"`
	Session   string        `json:"session"`
	Window    string        `json:"window"`
	Cwd       string        `json:"cwd"`
	Lane      string        `json:"lane"`
	Model     *string       `json:"model"`
	Source    string        `json:"source"`
	Status    string        `json:"status"`
	StartedAt time.Time     `json:"started_at"`
	SeenAt    *time.Time    `json:"seen_at"`
	EndedAt   *time.Time    `json:"ended_at"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type CcLaunchCounter struct {
	Week      time.Time `json:"week"`
	Count     int32     `json:"count"`
	UpdatedAt time.Time `json:"updated_at"`
}

type CcRouteDecision struct {
	ID             uuid.UUID       `json:"id"`
	UserID         uuid.NullUUID   `json:"user_id"`
	ConversationID uuid.NullUUID   `json:"conversation_id"`
	PromptSha256   string          `json:"prompt_sha256"`
	Features       json.RawMessage `json:"features"`
	Lane           string          `json:"lane"`
	Rule           string          `json:"rule"`
	Reason         string          `json:"reason"`
	Target         *string         `json:"target"`
	Model          *string         `json:"model"`
	DryRun         bool            `json:"dry_run"`
	JobID          *string         `json:"job_id"`
	RunID          uuid.NullUUID   `json:"run_id"`
	CreatedAt      time.Time       `json:"created_at"`
}

type Compaction struct {
	ID               uuid.UUID       `json:"id"`
	ConversationID   uuid.UUID       `json:"conversation_id"`
	CoversThroughSeq int64           `json:"covers_through_seq"`
	Block            json.RawMessage `json:"block"`
	TokenCount       int32           `json:"token_count"`
	EndpointID       *string         `json:"endpoint_id"`
	CreatedAt        time.Time       `json:"created_at"`
}

type Conversation struct {
	ID                       uuid.UUID       `json:"id"`
	ProjectID                uuid.UUID       `json:"project_id"`
	UserID                   uuid.UUID       `json:"user_id"`
	Title                    string          `json:"title"`
	Mode                     string          `json:"mode"`
	AgentID                  uuid.NullUUID   `json:"agent_id"`
	ModelSelector            string          `json:"model_selector"`
	Settings                 json.RawMessage `json:"settings"`
	CompactionHeadMessageSeq *int64          `json:"compaction_head_message_seq"`
	CreatedAt                time.Time       `json:"created_at"`
	UpdatedAt                time.Time       `json:"updated_at"`
	ArchivedAt               *time.Time      `json:"archived_at"`
}

type Dataset struct {
	ID           uuid.UUID       `json:"id"`
	OwnerID      uuid.UUID       `json:"owner_id"`
	Name         string          `json:"name"`
	TaskClass    string          `json:"task_class"`
	Filters      json.RawMessage `json:"filters"`
	Status       string          `json:"status"`
	BlobKey      *string         `json:"blob_key"`
	EvalBlobKey  *string         `json:"eval_blob_key"`
	Bytes        int64           `json:"bytes"`
	Examples     int32           `json:"examples"`
	EvalExamples int32           `json:"eval_examples"`
	Error        *string         `json:"error"`
	CreatedAt    time.Time       `json:"created_at"`
	BuiltAt      *time.Time      `json:"built_at"`
}

type Endpoint struct {
	ID              string          `json:"id"`
	ProviderID      string          `json:"provider_id"`
	ModelName       string          `json:"model_name"`
	DisplayName     string          `json:"display_name"`
	Capabilities    json.RawMessage `json:"capabilities"`
	Pricing         json.RawMessage `json:"pricing"`
	ThroughputClass string          `json:"throughput_class"`
	LatencyClass    string          `json:"latency_class"`
	IsLocal         bool            `json:"is_local"`
	Enabled         bool            `json:"enabled"`
	HealthStatus    string          `json:"health_status"`
	HealthCheckedAt *time.Time      `json:"health_checked_at"`
	HealthError     *string         `json:"health_error"`
	P50LatencyMs    *int32          `json:"p50_latency_ms"`
	ErrorRate       *float32        `json:"error_rate"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
	ExtraBody       json.RawMessage `json:"extra_body"`
}

type FinetuneJob struct {
	ID             uuid.UUID       `json:"id"`
	OwnerID        uuid.UUID       `json:"owner_id"`
	DatasetID      uuid.NullUUID   `json:"dataset_id"`
	BaseModel      string          `json:"base_model"`
	BaseEndpointID *string         `json:"base_endpoint_id"`
	AdapterName    string          `json:"adapter_name"`
	Config         json.RawMessage `json:"config"`
	Status         string          `json:"status"`
	Progress       float32         `json:"progress"`
	Log            string          `json:"log"`
	AdapterID      uuid.NullUUID   `json:"adapter_id"`
	Error          *string         `json:"error"`
	CreatedAt      time.Time       `json:"created_at"`
	StartedAt      *time.Time      `json:"started_at"`
	EndedAt        *time.Time      `json:"ended_at"`
}

type Invite struct {
	ID        uuid.UUID     `json:"id"`
	Email     string        `json:"email"`
	TokenHash []byte        `json:"token_hash"`
	InvitedBy uuid.NullUUID `json:"invited_by"`
	Role      string        `json:"role"`
	CreatedAt time.Time     `json:"created_at"`
	ExpiresAt time.Time     `json:"expires_at"`
	UsedAt    *time.Time    `json:"used_at"`
	UsedBy    uuid.NullUUID `json:"used_by"`
}

type MagicLink struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	TokenHash []byte     `json:"token_hash"`
	CreatedAt time.Time  `json:"created_at"`
	ExpiresAt time.Time  `json:"expires_at"`
	UsedAt    *time.Time `json:"used_at"`
}

type MediaJob struct {
	ID                  uuid.UUID       `json:"id"`
	UserID              uuid.UUID       `json:"user_id"`
	ProjectID           uuid.UUID       `json:"project_id"`
	ConversationID      uuid.NullUUID   `json:"conversation_id"`
	Kind                string          `json:"kind"`
	Selector            string          `json:"selector"`
	EndpointID          *string         `json:"endpoint_id"`
	Inputs              json.RawMessage `json:"inputs"`
	ProviderJobID       *string         `json:"provider_job_id"`
	Status              string          `json:"status"`
	Progress            float32         `json:"progress"`
	OutputAttachmentIds []uuid.UUID     `json:"output_attachment_ids"`
	CostUsd             float64         `json:"cost_usd"`
	Error               *string         `json:"error"`
	CreatedAt           time.Time       `json:"created_at"`
	StartedAt           *time.Time      `json:"started_at"`
	EndedAt             *time.Time      `json:"ended_at"`
	UpdatedAt           time.Time       `json:"updated_at"`
}

type Message struct {
	ID             uuid.UUID       `json:"id"`
	ConversationID uuid.UUID       `json:"conversation_id"`
	Seq            int64           `json:"seq"`
	Role           string          `json:"role"`
	Parts          json.RawMessage `json:"parts"`
	EndpointID     *string         `json:"endpoint_id"`
	Model          *string         `json:"model"`
	Usage          json.RawMessage `json:"usage"`
	FinishReason   *string         `json:"finish_reason"`
	ParentID       uuid.NullUUID   `json:"parent_id"`
	CreatedAt      time.Time       `json:"created_at"`
}

type MessageAttachment struct {
	MessageID    uuid.UUID `json:"message_id"`
	AttachmentID uuid.UUID `json:"attachment_id"`
}

type MessageRating struct {
	MessageID uuid.UUID `json:"message_id"`
	UserID    uuid.UUID `json:"user_id"`
	Score     int16     `json:"score"`
	Note      *string   `json:"note"`
	CreatedAt time.Time `json:"created_at"`
}

type Passkey struct {
	ID              uuid.UUID  `json:"id"`
	UserID          uuid.UUID  `json:"user_id"`
	CredentialID    []byte     `json:"credential_id"`
	PublicKey       []byte     `json:"public_key"`
	AttestationType string     `json:"attestation_type"`
	Transports      []string   `json:"transports"`
	Aaguid          []byte     `json:"aaguid"`
	SignCount       int64      `json:"sign_count"`
	BackupEligible  bool       `json:"backup_eligible"`
	BackupState     bool       `json:"backup_state"`
	Name            string     `json:"name"`
	CreatedAt       time.Time  `json:"created_at"`
	LastUsedAt      *time.Time `json:"last_used_at"`
}

type Project struct {
	ID                   uuid.UUID       `json:"id"`
	OwnerID              uuid.UUID       `json:"owner_id"`
	Name                 string          `json:"name"`
	Kind                 string          `json:"kind"`
	Settings             json.RawMessage `json:"settings"`
	RepoUrl              *string         `json:"repo_url"`
	DefaultBranch        *string         `json:"default_branch"`
	GithubInstallationID *int64          `json:"github_installation_id"`
	CreatedAt            time.Time       `json:"created_at"`
	UpdatedAt            time.Time       `json:"updated_at"`
	ArchivedAt           *time.Time      `json:"archived_at"`
}

type ProjectMember struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
	AddedAt   time.Time `json:"added_at"`
}

type Provider struct {
	ID        string          `json:"id"`
	Kind      string          `json:"kind"`
	Name      string          `json:"name"`
	BaseUrl   string          `json:"base_url"`
	ApiKeyEnv *string         `json:"api_key_env"`
	Headers   json.RawMessage `json:"headers"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type RentalInstance struct {
	ID                 uuid.UUID     `json:"id"`
	Provider           string        `json:"provider"`
	Template           string        `json:"template"`
	Gpu                string        `json:"gpu"`
	ProviderInstanceID *string       `json:"provider_instance_id"`
	EndpointID         string        `json:"endpoint_id"`
	BaseUrl            *string       `json:"base_url"`
	HourlyUsd          float64       `json:"hourly_usd"`
	Status             string        `json:"status"`
	StartedBy          uuid.NullUUID `json:"started_by"`
	StartedAt          time.Time     `json:"started_at"`
	ReadyAt            *time.Time    `json:"ready_at"`
	LastRequestAt      *time.Time    `json:"last_request_at"`
	StoppedAt          *time.Time    `json:"stopped_at"`
	HoursUsed          float32       `json:"hours_used"`
	BilledHours        float32       `json:"billed_hours"`
	StopReason         *string       `json:"stop_reason"`
	Error              *string       `json:"error"`
	CreatedAt          time.Time     `json:"created_at"`
	UpdatedAt          time.Time     `json:"updated_at"`
}

type RoutingPolicy struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Yaml      string    `json:"yaml"`
	Priority  int32     `json:"priority"`
	Enabled   bool      `json:"enabled"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Sandbox struct {
	ID          uuid.UUID `json:"id"`
	ProjectID   uuid.UUID `json:"project_id"`
	UserID      uuid.UUID `json:"user_id"`
	ContainerID *string   `json:"container_id"`
	VolumeName  string    `json:"volume_name"`
	Image       string    `json:"image"`
	Runtime     string    `json:"runtime"`
	Status      string    `json:"status"`
	Error       *string   `json:"error"`
	LastUsedAt  time.Time `json:"last_used_at"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type SandboxEvent struct {
	ID        int64           `json:"id"`
	SandboxID uuid.UUID       `json:"sandbox_id"`
	Kind      string          `json:"kind"`
	Detail    json.RawMessage `json:"detail"`
	CreatedAt time.Time       `json:"created_at"`
}

type Session struct {
	ID        uuid.UUID     `json:"id"`
	UserID    uuid.UUID     `json:"user_id"`
	TokenHash []byte        `json:"token_hash"`
	CreatedAt time.Time     `json:"created_at"`
	ExpiresAt time.Time     `json:"expires_at"`
	UserAgent string        `json:"user_agent"`
	Ip        *netip.Prefix `json:"ip"`
	RevokedAt *time.Time    `json:"revoked_at"`
}

type UsageLedger struct {
	ID               int64           `json:"id"`
	CreatedAt        time.Time       `json:"created_at"`
	UserID           uuid.NullUUID   `json:"user_id"`
	ConversationID   uuid.NullUUID   `json:"conversation_id"`
	AgentID          uuid.NullUUID   `json:"agent_id"`
	AgentRunID       uuid.NullUUID   `json:"agent_run_id"`
	ApiKeyID         uuid.NullUUID   `json:"api_key_id"`
	EndpointID       *string         `json:"endpoint_id"`
	Model            *string         `json:"model"`
	TaskClass        *string         `json:"task_class"`
	PolicyName       *string         `json:"policy_name"`
	Decision         json.RawMessage `json:"decision"`
	InputTokens      int32           `json:"input_tokens"`
	OutputTokens     int32           `json:"output_tokens"`
	CacheReadTokens  int32           `json:"cache_read_tokens"`
	CacheWriteTokens int32           `json:"cache_write_tokens"`
	CostUsd          float64         `json:"cost_usd"`
	LatencyMs        *int32          `json:"latency_ms"`
	TtftMs           *int32          `json:"ttft_ms"`
	FinishReason     *string         `json:"finish_reason"`
	Error            *string         `json:"error"`
	SessionID        *string         `json:"session_id"`
}

type User struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	DisplayName     string     `json:"display_name"`
	Role            string     `json:"role"`
	CreatedAt       time.Time  `json:"created_at"`
	DisabledAt      *time.Time `json:"disabled_at"`
	TrainingConsent bool       `json:"training_consent"`
}

type WebauthnSession struct {
	ID        uuid.UUID       `json:"id"`
	UserID    uuid.NullUUID   `json:"user_id"`
	Kind      string          `json:"kind"`
	Data      json.RawMessage `json:"data"`
	CreatedAt time.Time       `json:"created_at"`
	ExpiresAt time.Time       `json:"expires_at"`
}
