// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providerkeys.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteUserProviderKey = `-- name: DeleteUserProviderKey :exec
DELETE FROM user_provider_keys WHERE user_id = $1 AND provider_id = $2
`

type DeleteUserProviderKeyParams struct {
	UserID     uuid.UUID `json:"user_id"`
	ProviderID string    `json:"provider_id"`
}

func (q *Queries) DeleteUserProviderKey(ctx context.Context, arg DeleteUserProviderKeyParams) error {
	_, err := q.db.Exec(ctx, deleteUserProviderKey, arg.UserID, arg.ProviderID)
	return err
}

const getUserProviderKey = `-- name: GetUserProviderKey :one
SELECT user_id, provider_id, sealed, last4, created_at, updated_at FROM user_provider_keys WHERE user_id = $1 AND provider_id = $2
`

type GetUserProviderKeyParams struct {
	UserID     uuid.UUID `json:"user_id"`
	ProviderID string    `json:"provider_id"`
}

func (q *Queries) GetUserProviderKey(ctx context.Context, arg GetUserProviderKeyParams) (UserProviderKey, error) {
	row := q.db.QueryRow(ctx, getUserProviderKey, arg.UserID, arg.ProviderID)
	var i UserProviderKey
	err := row.Scan(
		&i.UserID,
		&i.ProviderID,
		&i.Sealed,
		&i.Last4,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserProviderKeys = `-- name: ListUserProviderKeys :many
SELECT provider_id, last4, created_at, updated_at FROM user_provider_keys WHERE user_id = $1 ORDER BY provider_id
`

type ListUserProviderKeysRow struct {
	ProviderID string    `json:"provider_id"`
	Last4      string    `json:"last4"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

// Metadata only; the sealed key is never listed.
func (q *Queries) ListUserProviderKeys(ctx context.Context, userID uuid.UUID) ([]ListUserProviderKeysRow, error) {
	rows, err := q.db.Query(ctx, listUserProviderKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserProviderKeysRow{}
	for rows.Next() {
		var i ListUserProviderKeysRow
		if err := rows.Scan(
			&i.ProviderID,
			&i.Last4,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserProviderKeysSealed = `-- name: ListUserProviderKeysSealed :many
SELECT provider_id, sealed FROM user_provider_keys WHERE user_id = $1
`

type ListUserProviderKeysSealedRow struct {
	ProviderID string `json:"provider_id"`
	Sealed     []byte `json:"sealed"`
}

// For the gateway only: the sealed keys of one user, opened in memory per call.
func (q *Queries) ListUserProviderKeysSealed(ctx context.Context, userID uuid.UUID) ([]ListUserProviderKeysSealedRow, error) {
	rows, err := q.db.Query(ctx, listUserProviderKeysSealed, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserProviderKeysSealedRow{}
	for rows.Next() {
		var i ListUserProviderKeysSealedRow
		if err := rows.Scan(&i.ProviderID, &i.Sealed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserSharedProviderKeys = `-- name: SetUserSharedProviderKeys :exec
UPDATE users SET shared_provider_keys = $2 WHERE id = $1
`

type SetUserSharedProviderKeysParams struct {
	ID                 uuid.UUID `json:"id"`
	SharedProviderKeys bool      `json:"shared_provider_keys"`
}

func (q *Queries) SetUserSharedProviderKeys(ctx context.Context, arg SetUserSharedProviderKeysParams) error {
	_, err := q.db.Exec(ctx, setUserSharedProviderKeys, arg.ID, arg.SharedProviderKeys)
	return err
}

const upsertUserProviderKey = `-- name: UpsertUserProviderKey :exec
INSERT INTO user_provider_keys (user_id, provider_id, sealed, last4)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, provider_id) DO UPDATE SET sealed = EXCLUDED.sealed, last4 = EXCLUDED.last4, updated_at = now()
`

type UpsertUserProviderKeyParams struct {
	UserID     uuid.UUID `json:"user_id"`
	ProviderID string    `json:"provider_id"`
	Sealed     []byte    `json:"sealed"`
	Last4      string    `json:"last4"`
}

func (q *Queries) UpsertUserProviderKey(ctx context.Context, arg UpsertUserProviderKeyParams) error {
	_, err := q.db.Exec(ctx, upsertUserProviderKey,
		arg.UserID,
		arg.ProviderID,
		arg.Sealed,
		arg.Last4,
	)
	return err
}
