// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rental.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRentalInstance = `-- name: CreateRentalInstance :one
INSERT INTO rental_instances (provider, template, gpu, provider_instance_id, endpoint_id, hourly_usd, started_by)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, provider, template, gpu, provider_instance_id, endpoint_id, base_url, hourly_usd, status, started_by, started_at, ready_at, last_request_at, stopped_at, hours_used, billed_hours, stop_reason, error, created_at, updated_at
`

type CreateRentalInstanceParams struct {
	Provider           string        `json:"provider"`
	Template           string        `json:"template"`
	Gpu                string        `json:"gpu"`
	ProviderInstanceID *string       `json:"provider_instance_id"`
	EndpointID         string        `json:"endpoint_id"`
	HourlyUsd          float64       `json:"hourly_usd"`
	StartedBy          uuid.NullUUID `json:"started_by"`
}

func (q *Queries) CreateRentalInstance(ctx context.Context, arg CreateRentalInstanceParams) (RentalInstance, error) {
	row := q.db.QueryRow(ctx, createRentalInstance,
		arg.Provider,
		arg.Template,
		arg.Gpu,
		arg.ProviderInstanceID,
		arg.EndpointID,
		arg.HourlyUsd,
		arg.StartedBy,
	)
	var i RentalInstance
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Template,
		&i.Gpu,
		&i.ProviderInstanceID,
		&i.EndpointID,
		&i.BaseUrl,
		&i.HourlyUsd,
		&i.Status,
		&i.StartedBy,
		&i.StartedAt,
		&i.ReadyAt,
		&i.LastRequestAt,
		&i.StoppedAt,
		&i.HoursUsed,
		&i.BilledHours,
		&i.StopReason,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRentalInstance = `-- name: GetRentalInstance :one
SELECT id, provider, template, gpu, provider_instance_id, endpoint_id, base_url, hourly_usd, status, started_by, started_at, ready_at, last_request_at, stopped_at, hours_used, billed_hours, stop_reason, error, created_at, updated_at FROM rental_instances WHERE id = $1
`

func (q *Queries) GetRentalInstance(ctx context.Context, id uuid.UUID) (RentalInstance, error) {
	row := q.db.QueryRow(ctx, getRentalInstance, id)
	var i RentalInstance
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Template,
		&i.Gpu,
		&i.ProviderInstanceID,
		&i.EndpointID,
		&i.BaseUrl,
		&i.HourlyUsd,
		&i.Status,
		&i.StartedBy,
		&i.StartedAt,
		&i.ReadyAt,
		&i.LastRequestAt,
		&i.StoppedAt,
		&i.HoursUsed,
		&i.BilledHours,
		&i.StopReason,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lastUsageForEndpoint = `-- name: LastUsageForEndpoint :one
SELECT COALESCE(MAX(created_at), '1970-01-01'::timestamptz)::timestamptz FROM usage_ledger WHERE endpoint_id = $1 AND task_class <> 'rental'
`

func (q *Queries) LastUsageForEndpoint(ctx context.Context, endpointID *string) (time.Time, error) {
	row := q.db.QueryRow(ctx, lastUsageForEndpoint, endpointID)
	var column_1 time.Time
	err := row.Scan(&column_1)
	return column_1, err
}

const listOpenRentalInstances = `-- name: ListOpenRentalInstances :many
SELECT id, provider, template, gpu, provider_instance_id, endpoint_id, base_url, hourly_usd, status, started_by, started_at, ready_at, last_request_at, stopped_at, hours_used, billed_hours, stop_reason, error, created_at, updated_at FROM rental_instances WHERE status IN ('provisioning','warming','ready','stopping') ORDER BY started_at
`

func (q *Queries) ListOpenRentalInstances(ctx context.Context) ([]RentalInstance, error) {
	rows, err := q.db.Query(ctx, listOpenRentalInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RentalInstance{}
	for rows.Next() {
		var i RentalInstance
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Template,
			&i.Gpu,
			&i.ProviderInstanceID,
			&i.EndpointID,
			&i.BaseUrl,
			&i.HourlyUsd,
			&i.Status,
			&i.StartedBy,
			&i.StartedAt,
			&i.ReadyAt,
			&i.LastRequestAt,
			&i.StoppedAt,
			&i.HoursUsed,
			&i.BilledHours,
			&i.StopReason,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRentalInstances = `-- name: ListRentalInstances :many
SELECT id, provider, template, gpu, provider_instance_id, endpoint_id, base_url, hourly_usd, status, started_by, started_at, ready_at, last_request_at, stopped_at, hours_used, billed_hours, stop_reason, error, created_at, updated_at FROM rental_instances ORDER BY started_at DESC LIMIT $1
`

func (q *Queries) ListRentalInstances(ctx context.Context, limit int32) ([]RentalInstance, error) {
	rows, err := q.db.Query(ctx, listRentalInstances, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RentalInstance{}
	for rows.Next() {
		var i RentalInstance
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Template,
			&i.Gpu,
			&i.ProviderInstanceID,
			&i.EndpointID,
			&i.BaseUrl,
			&i.HourlyUsd,
			&i.Status,
			&i.StartedBy,
			&i.StartedAt,
			&i.ReadyAt,
			&i.LastRequestAt,
			&i.StoppedAt,
			&i.HoursUsed,
			&i.BilledHours,
			&i.StopReason,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openRentalInstanceForTemplate = `-- name: OpenRentalInstanceForTemplate :one
SELECT id, provider, template, gpu, provider_instance_id, endpoint_id, base_url, hourly_usd, status, started_by, started_at, ready_at, last_request_at, stopped_at, hours_used, billed_hours, stop_reason, error, created_at, updated_at FROM rental_instances WHERE template = $1 AND status IN ('provisioning','warming','ready','stopping') ORDER BY started_at DESC LIMIT 1
`

func (q *Queries) OpenRentalInstanceForTemplate(ctx context.Context, template string) (RentalInstance, error) {
	row := q.db.QueryRow(ctx, openRentalInstanceForTemplate, template)
	var i RentalInstance
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Template,
		&i.Gpu,
		&i.ProviderInstanceID,
		&i.EndpointID,
		&i.BaseUrl,
		&i.HourlyUsd,
		&i.Status,
		&i.StartedBy,
		&i.StartedAt,
		&i.ReadyAt,
		&i.LastRequestAt,
		&i.StoppedAt,
		&i.HoursUsed,
		&i.BilledHours,
		&i.StopReason,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setRentalProviderID = `-- name: SetRentalProviderID :exec
UPDATE rental_instances SET provider_instance_id = $2 WHERE id = $1
`

type SetRentalProviderIDParams struct {
	ID                 uuid.UUID `json:"id"`
	ProviderInstanceID *string   `json:"provider_instance_id"`
}

func (q *Queries) SetRentalProviderID(ctx context.Context, arg SetRentalProviderIDParams) error {
	_, err := q.db.Exec(ctx, setRentalProviderID, arg.ID, arg.ProviderInstanceID)
	return err
}

const setRentalReady = `-- name: SetRentalReady :exec
UPDATE rental_instances SET status = 'ready', base_url = $2, ready_at = COALESCE(ready_at, now()),
  hourly_usd = CASE WHEN $3::numeric > 0 THEN $3::numeric ELSE hourly_usd END WHERE id = $1
`

type SetRentalReadyParams struct {
	ID        uuid.UUID `json:"id"`
	BaseUrl   *string   `json:"base_url"`
	HourlyUsd float64   `json:"hourly_usd"`
}

func (q *Queries) SetRentalReady(ctx context.Context, arg SetRentalReadyParams) error {
	_, err := q.db.Exec(ctx, setRentalReady, arg.ID, arg.BaseUrl, arg.HourlyUsd)
	return err
}

const setRentalStatus = `-- name: SetRentalStatus :exec
UPDATE rental_instances SET status = $2, error = COALESCE($3, error), stop_reason = COALESCE($4, stop_reason),
  stopped_at = CASE WHEN $2 IN ('stopped','failed') THEN COALESCE(stopped_at, now()) ELSE stopped_at END
WHERE id = $1
`

type SetRentalStatusParams struct {
	ID         uuid.UUID `json:"id"`
	Status     string    `json:"status"`
	Error      *string   `json:"error"`
	StopReason *string   `json:"stop_reason"`
}

func (q *Queries) SetRentalStatus(ctx context.Context, arg SetRentalStatusParams) error {
	_, err := q.db.Exec(ctx, setRentalStatus,
		arg.ID,
		arg.Status,
		arg.Error,
		arg.StopReason,
	)
	return err
}

const setRentalUsage = `-- name: SetRentalUsage :exec
UPDATE rental_instances SET hours_used = $2, billed_hours = $3, last_request_at = COALESCE($4, last_request_at) WHERE id = $1
`

type SetRentalUsageParams struct {
	ID            uuid.UUID  `json:"id"`
	HoursUsed     float32    `json:"hours_used"`
	BilledHours   float32    `json:"billed_hours"`
	LastRequestAt *time.Time `json:"last_request_at"`
}

func (q *Queries) SetRentalUsage(ctx context.Context, arg SetRentalUsageParams) error {
	_, err := q.db.Exec(ctx, setRentalUsage,
		arg.ID,
		arg.HoursUsed,
		arg.BilledHours,
		arg.LastRequestAt,
	)
	return err
}

const sumRentalHoursSince = `-- name: SumRentalHoursSince :one
SELECT COALESCE(SUM(hours_used), 0)::float8 FROM rental_instances WHERE started_at >= $1 OR status IN ('provisioning','warming','ready','stopping')
`

func (q *Queries) SumRentalHoursSince(ctx context.Context, startedAt time.Time) (float64, error) {
	row := q.db.QueryRow(ctx, sumRentalHoursSince, startedAt)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const touchRentalInstance = `-- name: TouchRentalInstance :exec
UPDATE rental_instances SET last_request_at = now() WHERE id = $1
`

func (q *Queries) TouchRentalInstance(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchRentalInstance, id)
	return err
}
