// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sandboxes.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deleteSandbox = `-- name: DeleteSandbox :exec
DELETE FROM sandboxes WHERE id = $1
`

func (q *Queries) DeleteSandbox(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSandbox, id)
	return err
}

const getSandbox = `-- name: GetSandbox :one
SELECT id, project_id, user_id, container_id, volume_name, image, runtime, status, error, last_used_at, created_at, updated_at FROM sandboxes WHERE project_id = $1 AND user_id = $2
`

type GetSandboxParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetSandbox(ctx context.Context, arg GetSandboxParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, getSandbox, arg.ProjectID, arg.UserID)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.ContainerID,
		&i.VolumeName,
		&i.Image,
		&i.Runtime,
		&i.Status,
		&i.Error,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSandboxByID = `-- name: GetSandboxByID :one
SELECT id, project_id, user_id, container_id, volume_name, image, runtime, status, error, last_used_at, created_at, updated_at FROM sandboxes WHERE id = $1
`

func (q *Queries) GetSandboxByID(ctx context.Context, id uuid.UUID) (Sandbox, error) {
	row := q.db.QueryRow(ctx, getSandboxByID, id)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.ContainerID,
		&i.VolumeName,
		&i.Image,
		&i.Runtime,
		&i.Status,
		&i.Error,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSandboxByShortID = `-- name: GetSandboxByShortID :one
SELECT id, project_id, user_id, container_id, volume_name, image, runtime, status, error, last_used_at, created_at, updated_at FROM sandboxes WHERE left(replace(id::text, '-', ''), 12) = $1::text
`

func (q *Queries) GetSandboxByShortID(ctx context.Context, short string) (Sandbox, error) {
	row := q.db.QueryRow(ctx, getSandboxByShortID, short)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.ContainerID,
		&i.VolumeName,
		&i.Image,
		&i.Runtime,
		&i.Status,
		&i.Error,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSandbox = `-- name: InsertSandbox :one
INSERT INTO sandboxes (project_id, user_id, volume_name, image, runtime)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, user_id, container_id, volume_name, image, runtime, status, error, last_used_at, created_at, updated_at
`

type InsertSandboxParams struct {
	ProjectID  uuid.UUID `json:"project_id"`
	UserID     uuid.UUID `json:"user_id"`
	VolumeName string    `json:"volume_name"`
	Image      string    `json:"image"`
	Runtime    string    `json:"runtime"`
}

func (q *Queries) InsertSandbox(ctx context.Context, arg InsertSandboxParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, insertSandbox,
		arg.ProjectID,
		arg.UserID,
		arg.VolumeName,
		arg.Image,
		arg.Runtime,
	)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.ContainerID,
		&i.VolumeName,
		&i.Image,
		&i.Runtime,
		&i.Status,
		&i.Error,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSandboxEvent = `-- name: InsertSandboxEvent :exec
INSERT INTO sandbox_events (sandbox_id, kind, detail) VALUES ($1, $2, $3)
`

type InsertSandboxEventParams struct {
	SandboxID uuid.UUID       `json:"sandbox_id"`
	Kind      string          `json:"kind"`
	Detail    json.RawMessage `json:"detail"`
}

func (q *Queries) InsertSandboxEvent(ctx context.Context, arg InsertSandboxEventParams) error {
	_, err := q.db.Exec(ctx, insertSandboxEvent, arg.SandboxID, arg.Kind, arg.Detail)
	return err
}

const listSandboxesForProject = `-- name: ListSandboxesForProject :many
SELECT id, project_id, user_id, container_id, volume_name, image, runtime, status, error, last_used_at, created_at, updated_at FROM sandboxes WHERE project_id = $1 ORDER BY created_at
`

func (q *Queries) ListSandboxesForProject(ctx context.Context, projectID uuid.UUID) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, listSandboxesForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.ContainerID,
			&i.VolumeName,
			&i.Image,
			&i.Runtime,
			&i.Status,
			&i.Error,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxesRunningIdleSince = `-- name: ListSandboxesRunningIdleSince :many
SELECT id, project_id, user_id, container_id, volume_name, image, runtime, status, error, last_used_at, created_at, updated_at FROM sandboxes WHERE status = 'running' AND last_used_at < $1 ORDER BY last_used_at
`

func (q *Queries) ListSandboxesRunningIdleSince(ctx context.Context, lastUsedAt time.Time) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, listSandboxesRunningIdleSince, lastUsedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.ContainerID,
			&i.VolumeName,
			&i.Image,
			&i.Runtime,
			&i.Status,
			&i.Error,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSandboxesStoppedSince = `-- name: ListSandboxesStoppedSince :many
SELECT id, project_id, user_id, container_id, volume_name, image, runtime, status, error, last_used_at, created_at, updated_at FROM sandboxes WHERE status IN ('stopped','failed') AND container_id IS NOT NULL AND last_used_at < $1 ORDER BY last_used_at
`

func (q *Queries) ListSandboxesStoppedSince(ctx context.Context, lastUsedAt time.Time) ([]Sandbox, error) {
	rows, err := q.db.Query(ctx, listSandboxesStoppedSince, lastUsedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sandbox{}
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.ContainerID,
			&i.VolumeName,
			&i.Image,
			&i.Runtime,
			&i.Status,
			&i.Error,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProjectInstallation = `-- name: SetProjectInstallation :exec
UPDATE projects SET github_installation_id = $2, updated_at = now() WHERE id = $1
`

type SetProjectInstallationParams struct {
	ID                   uuid.UUID `json:"id"`
	GithubInstallationID *int64    `json:"github_installation_id"`
}

func (q *Queries) SetProjectInstallation(ctx context.Context, arg SetProjectInstallationParams) error {
	_, err := q.db.Exec(ctx, setProjectInstallation, arg.ID, arg.GithubInstallationID)
	return err
}

const setProjectRepo = `-- name: SetProjectRepo :exec
UPDATE projects SET repo_url = $2, default_branch = $3, updated_at = now() WHERE id = $1
`

type SetProjectRepoParams struct {
	ID            uuid.UUID `json:"id"`
	RepoUrl       *string   `json:"repo_url"`
	DefaultBranch *string   `json:"default_branch"`
}

func (q *Queries) SetProjectRepo(ctx context.Context, arg SetProjectRepoParams) error {
	_, err := q.db.Exec(ctx, setProjectRepo, arg.ID, arg.RepoUrl, arg.DefaultBranch)
	return err
}

const setSandboxContainer = `-- name: SetSandboxContainer :exec
UPDATE sandboxes SET container_id = $2, status = $3, error = NULL, last_used_at = now(), updated_at = now() WHERE id = $1
`

type SetSandboxContainerParams struct {
	ID          uuid.UUID `json:"id"`
	ContainerID *string   `json:"container_id"`
	Status      string    `json:"status"`
}

func (q *Queries) SetSandboxContainer(ctx context.Context, arg SetSandboxContainerParams) error {
	_, err := q.db.Exec(ctx, setSandboxContainer, arg.ID, arg.ContainerID, arg.Status)
	return err
}

const setSandboxStatus = `-- name: SetSandboxStatus :exec
UPDATE sandboxes SET status = $2, error = $3, updated_at = now() WHERE id = $1
`

type SetSandboxStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
	Error  *string   `json:"error"`
}

func (q *Queries) SetSandboxStatus(ctx context.Context, arg SetSandboxStatusParams) error {
	_, err := q.db.Exec(ctx, setSandboxStatus, arg.ID, arg.Status, arg.Error)
	return err
}

const touchSandbox = `-- name: TouchSandbox :exec
UPDATE sandboxes SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchSandbox(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSandbox, id)
	return err
}
