// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: training.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const cancelFinetuneJob = `-- name: CancelFinetuneJob :exec
UPDATE finetune_jobs SET status = 'cancelled', ended_at = now() WHERE id = $1 AND status IN ('queued','running')
`

func (q *Queries) CancelFinetuneJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelFinetuneJob, id)
	return err
}

const claimFinetuneJob = `-- name: ClaimFinetuneJob :one
UPDATE finetune_jobs SET status = 'running', started_at = now() WHERE id = $1 AND status = 'queued' RETURNING id, owner_id, dataset_id, base_model, base_endpoint_id, adapter_name, config, status, progress, log, adapter_id, error, created_at, started_at, ended_at
`

func (q *Queries) ClaimFinetuneJob(ctx context.Context, id uuid.UUID) (FinetuneJob, error) {
	row := q.db.QueryRow(ctx, claimFinetuneJob, id)
	var i FinetuneJob
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.DatasetID,
		&i.BaseModel,
		&i.BaseEndpointID,
		&i.AdapterName,
		&i.Config,
		&i.Status,
		&i.Progress,
		&i.Log,
		&i.AdapterID,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const createAdapter = `-- name: CreateAdapter :one
INSERT INTO adapters (name, base_model, base_endpoint_id, finetune_job_id, blob_key, bytes, endpoint_id)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, name, base_model, base_endpoint_id, finetune_job_id, blob_key, bytes, eval_score, baseline_score, eval, promoted, endpoint_id, created_at, evaluated_at
`

type CreateAdapterParams struct {
	Name           string        `json:"name"`
	BaseModel      string        `json:"base_model"`
	BaseEndpointID *string       `json:"base_endpoint_id"`
	FinetuneJobID  uuid.NullUUID `json:"finetune_job_id"`
	BlobKey        string        `json:"blob_key"`
	Bytes          int64         `json:"bytes"`
	EndpointID     *string       `json:"endpoint_id"`
}

func (q *Queries) CreateAdapter(ctx context.Context, arg CreateAdapterParams) (Adapter, error) {
	row := q.db.QueryRow(ctx, createAdapter,
		arg.Name,
		arg.BaseModel,
		arg.BaseEndpointID,
		arg.FinetuneJobID,
		arg.BlobKey,
		arg.Bytes,
		arg.EndpointID,
	)
	var i Adapter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseModel,
		&i.BaseEndpointID,
		&i.FinetuneJobID,
		&i.BlobKey,
		&i.Bytes,
		&i.EvalScore,
		&i.BaselineScore,
		&i.Eval,
		&i.Promoted,
		&i.EndpointID,
		&i.CreatedAt,
		&i.EvaluatedAt,
	)
	return i, err
}

const createDataset = `-- name: CreateDataset :one
INSERT INTO datasets (owner_id, name, task_class, filters) VALUES ($1, $2, $3, $4) RETURNING id, owner_id, name, task_class, filters, status, blob_key, eval_blob_key, bytes, examples, eval_examples, error, created_at, built_at
`

type CreateDatasetParams struct {
	OwnerID   uuid.UUID       `json:"owner_id"`
	Name      string          `json:"name"`
	TaskClass string          `json:"task_class"`
	Filters   json.RawMessage `json:"filters"`
}

func (q *Queries) CreateDataset(ctx context.Context, arg CreateDatasetParams) (Dataset, error) {
	row := q.db.QueryRow(ctx, createDataset,
		arg.OwnerID,
		arg.Name,
		arg.TaskClass,
		arg.Filters,
	)
	var i Dataset
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.TaskClass,
		&i.Filters,
		&i.Status,
		&i.BlobKey,
		&i.EvalBlobKey,
		&i.Bytes,
		&i.Examples,
		&i.EvalExamples,
		&i.Error,
		&i.CreatedAt,
		&i.BuiltAt,
	)
	return i, err
}

const createFinetuneJob = `-- name: CreateFinetuneJob :one
INSERT INTO finetune_jobs (owner_id, dataset_id, base_model, base_endpoint_id, adapter_name, config)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, owner_id, dataset_id, base_model, base_endpoint_id, adapter_name, config, status, progress, log, adapter_id, error, created_at, started_at, ended_at
`

type CreateFinetuneJobParams struct {
	OwnerID        uuid.UUID       `json:"owner_id"`
	DatasetID      uuid.NullUUID   `json:"dataset_id"`
	BaseModel      string          `json:"base_model"`
	BaseEndpointID *string         `json:"base_endpoint_id"`
	AdapterName    string          `json:"adapter_name"`
	Config         json.RawMessage `json:"config"`
}

func (q *Queries) CreateFinetuneJob(ctx context.Context, arg CreateFinetuneJobParams) (FinetuneJob, error) {
	row := q.db.QueryRow(ctx, createFinetuneJob,
		arg.OwnerID,
		arg.DatasetID,
		arg.BaseModel,
		arg.BaseEndpointID,
		arg.AdapterName,
		arg.Config,
	)
	var i FinetuneJob
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.DatasetID,
		&i.BaseModel,
		&i.BaseEndpointID,
		&i.AdapterName,
		&i.Config,
		&i.Status,
		&i.Progress,
		&i.Log,
		&i.AdapterID,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const deleteAdapter = `-- name: DeleteAdapter :exec
DELETE FROM adapters WHERE id = $1
`

func (q *Queries) DeleteAdapter(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAdapter, id)
	return err
}

const deleteDataset = `-- name: DeleteDataset :exec
DELETE FROM datasets WHERE id = $1
`

func (q *Queries) DeleteDataset(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDataset, id)
	return err
}

const deleteMessageRating = `-- name: DeleteMessageRating :exec
DELETE FROM message_ratings WHERE message_id = $1 AND user_id = $2
`

type DeleteMessageRatingParams struct {
	MessageID uuid.UUID `json:"message_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteMessageRating(ctx context.Context, arg DeleteMessageRatingParams) error {
	_, err := q.db.Exec(ctx, deleteMessageRating, arg.MessageID, arg.UserID)
	return err
}

const finishDataset = `-- name: FinishDataset :exec
UPDATE datasets SET status = 'ready', error = NULL, blob_key = $2, eval_blob_key = $3, bytes = $4, examples = $5, eval_examples = $6, built_at = now()
WHERE id = $1
`

type FinishDatasetParams struct {
	ID           uuid.UUID `json:"id"`
	BlobKey      *string   `json:"blob_key"`
	EvalBlobKey  *string   `json:"eval_blob_key"`
	Bytes        int64     `json:"bytes"`
	Examples     int32     `json:"examples"`
	EvalExamples int32     `json:"eval_examples"`
}

func (q *Queries) FinishDataset(ctx context.Context, arg FinishDatasetParams) error {
	_, err := q.db.Exec(ctx, finishDataset,
		arg.ID,
		arg.BlobKey,
		arg.EvalBlobKey,
		arg.Bytes,
		arg.Examples,
		arg.EvalExamples,
	)
	return err
}

const finishFinetuneJob = `-- name: FinishFinetuneJob :exec
UPDATE finetune_jobs SET status = $2, error = $3, adapter_id = $4, progress = CASE WHEN $2 = 'done' THEN 1 ELSE progress END, log = $5, ended_at = now()
WHERE id = $1
`

type FinishFinetuneJobParams struct {
	ID        uuid.UUID     `json:"id"`
	Status    string        `json:"status"`
	Error     *string       `json:"error"`
	AdapterID uuid.NullUUID `json:"adapter_id"`
	Log       string        `json:"log"`
}

func (q *Queries) FinishFinetuneJob(ctx context.Context, arg FinishFinetuneJobParams) error {
	_, err := q.db.Exec(ctx, finishFinetuneJob,
		arg.ID,
		arg.Status,
		arg.Error,
		arg.AdapterID,
		arg.Log,
	)
	return err
}

const getAdapter = `-- name: GetAdapter :one
SELECT id, name, base_model, base_endpoint_id, finetune_job_id, blob_key, bytes, eval_score, baseline_score, eval, promoted, endpoint_id, created_at, evaluated_at FROM adapters WHERE id = $1
`

func (q *Queries) GetAdapter(ctx context.Context, id uuid.UUID) (Adapter, error) {
	row := q.db.QueryRow(ctx, getAdapter, id)
	var i Adapter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseModel,
		&i.BaseEndpointID,
		&i.FinetuneJobID,
		&i.BlobKey,
		&i.Bytes,
		&i.EvalScore,
		&i.BaselineScore,
		&i.Eval,
		&i.Promoted,
		&i.EndpointID,
		&i.CreatedAt,
		&i.EvaluatedAt,
	)
	return i, err
}

const getDataset = `-- name: GetDataset :one
SELECT id, owner_id, name, task_class, filters, status, blob_key, eval_blob_key, bytes, examples, eval_examples, error, created_at, built_at FROM datasets WHERE id = $1
`

func (q *Queries) GetDataset(ctx context.Context, id uuid.UUID) (Dataset, error) {
	row := q.db.QueryRow(ctx, getDataset, id)
	var i Dataset
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.TaskClass,
		&i.Filters,
		&i.Status,
		&i.BlobKey,
		&i.EvalBlobKey,
		&i.Bytes,
		&i.Examples,
		&i.EvalExamples,
		&i.Error,
		&i.CreatedAt,
		&i.BuiltAt,
	)
	return i, err
}

const getFinetuneJob = `-- name: GetFinetuneJob :one
SELECT id, owner_id, dataset_id, base_model, base_endpoint_id, adapter_name, config, status, progress, log, adapter_id, error, created_at, started_at, ended_at FROM finetune_jobs WHERE id = $1
`

func (q *Queries) GetFinetuneJob(ctx context.Context, id uuid.UUID) (FinetuneJob, error) {
	row := q.db.QueryRow(ctx, getFinetuneJob, id)
	var i FinetuneJob
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.DatasetID,
		&i.BaseModel,
		&i.BaseEndpointID,
		&i.AdapterName,
		&i.Config,
		&i.Status,
		&i.Progress,
		&i.Log,
		&i.AdapterID,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const listAdapters = `-- name: ListAdapters :many
SELECT id, name, base_model, base_endpoint_id, finetune_job_id, blob_key, bytes, eval_score, baseline_score, eval, promoted, endpoint_id, created_at, evaluated_at FROM adapters ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListAdapters(ctx context.Context, limit int32) ([]Adapter, error) {
	rows, err := q.db.Query(ctx, listAdapters, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Adapter{}
	for rows.Next() {
		var i Adapter
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseModel,
			&i.BaseEndpointID,
			&i.FinetuneJobID,
			&i.BlobKey,
			&i.Bytes,
			&i.EvalScore,
			&i.BaselineScore,
			&i.Eval,
			&i.Promoted,
			&i.EndpointID,
			&i.CreatedAt,
			&i.EvaluatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatasets = `-- name: ListDatasets :many
SELECT id, owner_id, name, task_class, filters, status, blob_key, eval_blob_key, bytes, examples, eval_examples, error, created_at, built_at FROM datasets ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListDatasets(ctx context.Context, limit int32) ([]Dataset, error) {
	rows, err := q.db.Query(ctx, listDatasets, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dataset{}
	for rows.Next() {
		var i Dataset
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.TaskClass,
			&i.Filters,
			&i.Status,
			&i.BlobKey,
			&i.EvalBlobKey,
			&i.Bytes,
			&i.Examples,
			&i.EvalExamples,
			&i.Error,
			&i.CreatedAt,
			&i.BuiltAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFinetuneJobs = `-- name: ListFinetuneJobs :many
SELECT id, owner_id, dataset_id, base_model, base_endpoint_id, adapter_name, config, status, progress, log, adapter_id, error, created_at, started_at, ended_at FROM finetune_jobs ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListFinetuneJobs(ctx context.Context, limit int32) ([]FinetuneJob, error) {
	rows, err := q.db.Query(ctx, listFinetuneJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FinetuneJob{}
	for rows.Next() {
		var i FinetuneJob
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.DatasetID,
			&i.BaseModel,
			&i.BaseEndpointID,
			&i.AdapterName,
			&i.Config,
			&i.Status,
			&i.Progress,
			&i.Log,
			&i.AdapterID,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRatingsForConversation = `-- name: ListRatingsForConversation :many
SELECT r.message_id, r.user_id, r.score, r.note, r.created_at
FROM message_ratings r JOIN messages m ON m.id = r.message_id
WHERE m.conversation_id = $1
`

func (q *Queries) ListRatingsForConversation(ctx context.Context, conversationID uuid.UUID) ([]MessageRating, error) {
	rows, err := q.db.Query(ctx, listRatingsForConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessageRating{}
	for rows.Next() {
		var i MessageRating
		if err := rows.Scan(
			&i.MessageID,
			&i.UserID,
			&i.Score,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrainingConversations = `-- name: ListTrainingConversations :many
SELECT c.id, c.project_id, c.user_id, c.title, c.mode, c.agent_id, c.model_selector, c.settings, c.compaction_head_message_seq, c.created_at, c.updated_at, c.archived_at FROM conversations c JOIN users u ON u.id = c.user_id
WHERE u.training_consent AND c.archived_at IS NULL
  AND (cardinality($1::text[]) = 0 OR c.mode = ANY($1::text[]))
  AND c.updated_at >= $2
ORDER BY c.created_at
LIMIT $3
`

type ListTrainingConversationsParams struct {
	Modes            []string  `json:"modes"`
	Since            time.Time `json:"since"`
	MaxConversations int32     `json:"max_conversations"`
}

// Conversations exportable into a dataset: the user opted in, the
// conversation is not archived, it is in one of the modes (an empty list
// takes every mode) and was last active since the cutoff.
func (q *Queries) ListTrainingConversations(ctx context.Context, arg ListTrainingConversationsParams) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listTrainingConversations, arg.Modes, arg.Since, arg.MaxConversations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Title,
			&i.Mode,
			&i.AgentID,
			&i.ModelSelector,
			&i.Settings,
			&i.CompactionHeadMessageSeq,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAdapterEval = `-- name: SetAdapterEval :exec
UPDATE adapters SET eval_score = $2, baseline_score = $3, eval = $4, evaluated_at = now() WHERE id = $1
`

type SetAdapterEvalParams struct {
	ID            uuid.UUID       `json:"id"`
	EvalScore     *float32        `json:"eval_score"`
	BaselineScore *float32        `json:"baseline_score"`
	Eval          json.RawMessage `json:"eval"`
}

func (q *Queries) SetAdapterEval(ctx context.Context, arg SetAdapterEvalParams) error {
	_, err := q.db.Exec(ctx, setAdapterEval,
		arg.ID,
		arg.EvalScore,
		arg.BaselineScore,
		arg.Eval,
	)
	return err
}

const setAdapterPromoted = `-- name: SetAdapterPromoted :exec
UPDATE adapters SET promoted = $2 WHERE id = $1
`

type SetAdapterPromotedParams struct {
	ID       uuid.UUID `json:"id"`
	Promoted bool      `json:"promoted"`
}

func (q *Queries) SetAdapterPromoted(ctx context.Context, arg SetAdapterPromotedParams) error {
	_, err := q.db.Exec(ctx, setAdapterPromoted, arg.ID, arg.Promoted)
	return err
}

const setDatasetStatus = `-- name: SetDatasetStatus :exec
UPDATE datasets SET status = $2, error = $3 WHERE id = $1
`

type SetDatasetStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
	Error  *string   `json:"error"`
}

func (q *Queries) SetDatasetStatus(ctx context.Context, arg SetDatasetStatusParams) error {
	_, err := q.db.Exec(ctx, setDatasetStatus, arg.ID, arg.Status, arg.Error)
	return err
}

const setFinetuneProgress = `-- name: SetFinetuneProgress :exec
UPDATE finetune_jobs SET progress = $2, log = $3 WHERE id = $1
`

type SetFinetuneProgressParams struct {
	ID       uuid.UUID `json:"id"`
	Progress float32   `json:"progress"`
	Log      string    `json:"log"`
}

func (q *Queries) SetFinetuneProgress(ctx context.Context, arg SetFinetuneProgressParams) error {
	_, err := q.db.Exec(ctx, setFinetuneProgress, arg.ID, arg.Progress, arg.Log)
	return err
}

const setTrainingConsent = `-- name: SetTrainingConsent :exec

UPDATE users SET training_consent = $2 WHERE id = $1
`

type SetTrainingConsentParams struct {
	ID              uuid.UUID `json:"id"`
	TrainingConsent bool      `json:"training_consent"`
}

// Training flywheel (PLAN.md M10): consent, ratings, datasets, fine-tune
// jobs and adapters.
func (q *Queries) SetTrainingConsent(ctx context.Context, arg SetTrainingConsentParams) error {
	_, err := q.db.Exec(ctx, setTrainingConsent, arg.ID, arg.TrainingConsent)
	return err
}

const upsertMessageRating = `-- name: UpsertMessageRating :exec
INSERT INTO message_ratings (message_id, user_id, score, note) VALUES ($1, $2, $3, $4)
ON CONFLICT (message_id, user_id) DO UPDATE SET score = EXCLUDED.score, note = EXCLUDED.note, created_at = now()
`

type UpsertMessageRatingParams struct {
	MessageID uuid.UUID `json:"message_id"`
	UserID    uuid.UUID `json:"user_id"`
	Score     int16     `json:"score"`
	Note      *string   `json:"note"`
}

func (q *Queries) UpsertMessageRating(ctx context.Context, arg UpsertMessageRatingParams) error {
	_, err := q.db.Exec(ctx, upsertMessageRating,
		arg.MessageID,
		arg.UserID,
		arg.Score,
		arg.Note,
	)
	return err
}
