// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const archiveConversation = `-- name: ArchiveConversation :exec
UPDATE conversations SET archived_at = now() WHERE id = $1
`

func (q *Queries) ArchiveConversation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveConversation, id)
	return err
}

const archiveProject = `-- name: ArchiveProject :exec
UPDATE projects SET archived_at = now() WHERE id = $1
`

func (q *Queries) ArchiveProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveProject, id)
	return err
}

const bumpArtifactVersion = `-- name: BumpArtifactVersion :one
UPDATE artifacts SET current_version = current_version + 1, title = COALESCE(NULLIF($2, ''), title)
WHERE id = $1 RETURNING current_version
`

type BumpArtifactVersionParams struct {
	ID      uuid.UUID   `json:"id"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) BumpArtifactVersion(ctx context.Context, arg BumpArtifactVersionParams) (int32, error) {
	row := q.db.QueryRow(ctx, bumpArtifactVersion, arg.ID, arg.Column2)
	var current_version int32
	err := row.Scan(&current_version)
	return current_version, err
}

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts (conversation_id, kind, title, language) VALUES ($1, $2, $3, $4) RETURNING id, conversation_id, kind, title, language, current_version, created_at, updated_at
`

type CreateArtifactParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	Kind           string    `json:"kind"`
	Title          string    `json:"title"`
	Language       *string   `json:"language"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.ConversationID,
		arg.Kind,
		arg.Title,
		arg.Language,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Kind,
		&i.Title,
		&i.Language,
		&i.CurrentVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (user_id, blob_key, mime, bytes, sha256, filename, width, height)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, user_id, blob_key, mime, bytes, sha256, filename, width, height, created_at
`

type CreateAttachmentParams struct {
	UserID   uuid.UUID `json:"user_id"`
	BlobKey  string    `json:"blob_key"`
	Mime     string    `json:"mime"`
	Bytes    int64     `json:"bytes"`
	Sha256   []byte    `json:"sha256"`
	Filename string    `json:"filename"`
	Width    *int32    `json:"width"`
	Height   *int32    `json:"height"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.UserID,
		arg.BlobKey,
		arg.Mime,
		arg.Bytes,
		arg.Sha256,
		arg.Filename,
		arg.Width,
		arg.Height,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BlobKey,
		&i.Mime,
		&i.Bytes,
		&i.Sha256,
		&i.Filename,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
	)
	return i, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (project_id, user_id, title, mode, model_selector, settings)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, project_id, user_id, title, mode, agent_id, model_selector, settings, compaction_head_message_seq, created_at, updated_at, archived_at
`

type CreateConversationParams struct {
	ProjectID     uuid.UUID       `json:"project_id"`
	UserID        uuid.UUID       `json:"user_id"`
	Title         string          `json:"title"`
	Mode          string          `json:"mode"`
	ModelSelector string          `json:"model_selector"`
	Settings      json.RawMessage `json:"settings"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.ProjectID,
		arg.UserID,
		arg.Title,
		arg.Mode,
		arg.ModelSelector,
		arg.Settings,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Title,
		&i.Mode,
		&i.AgentID,
		&i.ModelSelector,
		&i.Settings,
		&i.CompactionHeadMessageSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (owner_id, name, kind, settings) VALUES ($1, $2, $3, $4) RETURNING id, owner_id, name, kind, settings, repo_url, default_branch, github_installation_id, created_at, updated_at, archived_at
`

type CreateProjectParams struct {
	OwnerID  uuid.UUID       `json:"owner_id"`
	Name     string          `json:"name"`
	Kind     string          `json:"kind"`
	Settings json.RawMessage `json:"settings"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.OwnerID,
		arg.Name,
		arg.Kind,
		arg.Settings,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Kind,
		&i.Settings,
		&i.RepoUrl,
		&i.DefaultBranch,
		&i.GithubInstallationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const deleteMessagesFromSeq = `-- name: DeleteMessagesFromSeq :exec
DELETE FROM messages WHERE conversation_id = $1 AND seq >= $2
`

type DeleteMessagesFromSeqParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	Seq            int64     `json:"seq"`
}

func (q *Queries) DeleteMessagesFromSeq(ctx context.Context, arg DeleteMessagesFromSeqParams) error {
	_, err := q.db.Exec(ctx, deleteMessagesFromSeq, arg.ConversationID, arg.Seq)
	return err
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, conversation_id, kind, title, language, current_version, created_at, updated_at FROM artifacts WHERE id = $1
`

func (q *Queries) GetArtifact(ctx context.Context, id uuid.UUID) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Kind,
		&i.Title,
		&i.Language,
		&i.CurrentVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArtifactConversation = `-- name: GetArtifactConversation :one
SELECT c.id, c.project_id, c.user_id, c.title, c.mode, c.agent_id, c.model_selector, c.settings, c.compaction_head_message_seq, c.created_at, c.updated_at, c.archived_at FROM conversations c JOIN artifacts a ON a.conversation_id = c.id WHERE a.id = $1
`

func (q *Queries) GetArtifactConversation(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getArtifactConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Title,
		&i.Mode,
		&i.AgentID,
		&i.ModelSelector,
		&i.Settings,
		&i.CompactionHeadMessageSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getArtifactVersion = `-- name: GetArtifactVersion :one
SELECT id, artifact_id, version, content, blob_key, design_context, created_by_message_id, created_at FROM artifact_versions WHERE artifact_id = $1 AND version = $2
`

type GetArtifactVersionParams struct {
	ArtifactID uuid.UUID `json:"artifact_id"`
	Version    int32     `json:"version"`
}

func (q *Queries) GetArtifactVersion(ctx context.Context, arg GetArtifactVersionParams) (ArtifactVersion, error) {
	row := q.db.QueryRow(ctx, getArtifactVersion, arg.ArtifactID, arg.Version)
	var i ArtifactVersion
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.Version,
		&i.Content,
		&i.BlobKey,
		&i.DesignContext,
		&i.CreatedByMessageID,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifactVersionByID = `-- name: GetArtifactVersionByID :one
SELECT id, artifact_id, version, content, blob_key, design_context, created_by_message_id, created_at FROM artifact_versions WHERE id = $1
`

func (q *Queries) GetArtifactVersionByID(ctx context.Context, id uuid.UUID) (ArtifactVersion, error) {
	row := q.db.QueryRow(ctx, getArtifactVersionByID, id)
	var i ArtifactVersion
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.Version,
		&i.Content,
		&i.BlobKey,
		&i.DesignContext,
		&i.CreatedByMessageID,
		&i.CreatedAt,
	)
	return i, err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, user_id, blob_key, mime, bytes, sha256, filename, width, height, created_at FROM attachments WHERE id = $1
`

func (q *Queries) GetAttachment(ctx context.Context, id uuid.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BlobKey,
		&i.Mime,
		&i.Bytes,
		&i.Sha256,
		&i.Filename,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, project_id, user_id, title, mode, agent_id, model_selector, settings, compaction_head_message_seq, created_at, updated_at, archived_at FROM conversations WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) GetConversation(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Title,
		&i.Mode,
		&i.AgentID,
		&i.ModelSelector,
		&i.Settings,
		&i.CompactionHeadMessageSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, conversation_id, seq, role, parts, endpoint_id, model, usage, finish_reason, parent_id, created_at FROM messages WHERE id = $1
`

func (q *Queries) GetMessage(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Seq,
		&i.Role,
		&i.Parts,
		&i.EndpointID,
		&i.Model,
		&i.Usage,
		&i.FinishReason,
		&i.ParentID,
		&i.CreatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, owner_id, name, kind, settings, repo_url, default_branch, github_installation_id, created_at, updated_at, archived_at FROM projects WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Kind,
		&i.Settings,
		&i.RepoUrl,
		&i.DefaultBranch,
		&i.GithubInstallationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const insertArtifactVersion = `-- name: InsertArtifactVersion :one
INSERT INTO artifact_versions (artifact_id, version, content, blob_key, design_context, created_by_message_id)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, artifact_id, version, content, blob_key, design_context, created_by_message_id, created_at
`

type InsertArtifactVersionParams struct {
	ArtifactID         uuid.UUID       `json:"artifact_id"`
	Version            int32           `json:"version"`
	Content            *string         `json:"content"`
	BlobKey            *string         `json:"blob_key"`
	DesignContext      json.RawMessage `json:"design_context"`
	CreatedByMessageID uuid.NullUUID   `json:"created_by_message_id"`
}

func (q *Queries) InsertArtifactVersion(ctx context.Context, arg InsertArtifactVersionParams) (ArtifactVersion, error) {
	row := q.db.QueryRow(ctx, insertArtifactVersion,
		arg.ArtifactID,
		arg.Version,
		arg.Content,
		arg.BlobKey,
		arg.DesignContext,
		arg.CreatedByMessageID,
	)
	var i ArtifactVersion
	err := row.Scan(
		&i.ID,
		&i.ArtifactID,
		&i.Version,
		&i.Content,
		&i.BlobKey,
		&i.DesignContext,
		&i.CreatedByMessageID,
		&i.CreatedAt,
	)
	return i, err
}

const insertCompaction = `-- name: InsertCompaction :one
INSERT INTO compactions (conversation_id, covers_through_seq, block, token_count, endpoint_id)
VALUES ($1, $2, $3, $4, $5) RETURNING id, conversation_id, covers_through_seq, block, token_count, endpoint_id, created_at
`

type InsertCompactionParams struct {
	ConversationID   uuid.UUID       `json:"conversation_id"`
	CoversThroughSeq int64           `json:"covers_through_seq"`
	Block            json.RawMessage `json:"block"`
	TokenCount       int32           `json:"token_count"`
	EndpointID       *string         `json:"endpoint_id"`
}

func (q *Queries) InsertCompaction(ctx context.Context, arg InsertCompactionParams) (Compaction, error) {
	row := q.db.QueryRow(ctx, insertCompaction,
		arg.ConversationID,
		arg.CoversThroughSeq,
		arg.Block,
		arg.TokenCount,
		arg.EndpointID,
	)
	var i Compaction
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.CoversThroughSeq,
		&i.Block,
		&i.TokenCount,
		&i.EndpointID,
		&i.CreatedAt,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (conversation_id, seq, role, parts, endpoint_id, model, usage, finish_reason, parent_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, conversation_id, seq, role, parts, endpoint_id, model, usage, finish_reason, parent_id, created_at
`

type InsertMessageParams struct {
	ConversationID uuid.UUID       `json:"conversation_id"`
	Seq            int64           `json:"seq"`
	Role           string          `json:"role"`
	Parts          json.RawMessage `json:"parts"`
	EndpointID     *string         `json:"endpoint_id"`
	Model          *string         `json:"model"`
	Usage          json.RawMessage `json:"usage"`
	FinishReason   *string         `json:"finish_reason"`
	ParentID       uuid.NullUUID   `json:"parent_id"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.ConversationID,
		arg.Seq,
		arg.Role,
		arg.Parts,
		arg.EndpointID,
		arg.Model,
		arg.Usage,
		arg.FinishReason,
		arg.ParentID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Seq,
		&i.Role,
		&i.Parts,
		&i.EndpointID,
		&i.Model,
		&i.Usage,
		&i.FinishReason,
		&i.ParentID,
		&i.CreatedAt,
	)
	return i, err
}

const latestCompaction = `-- name: LatestCompaction :one
SELECT id, conversation_id, covers_through_seq, block, token_count, endpoint_id, created_at FROM compactions WHERE conversation_id = $1 ORDER BY covers_through_seq DESC LIMIT 1
`

func (q *Queries) LatestCompaction(ctx context.Context, conversationID uuid.UUID) (Compaction, error) {
	row := q.db.QueryRow(ctx, latestCompaction, conversationID)
	var i Compaction
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.CoversThroughSeq,
		&i.Block,
		&i.TokenCount,
		&i.EndpointID,
		&i.CreatedAt,
	)
	return i, err
}

const linkMessageAttachment = `-- name: LinkMessageAttachment :exec
INSERT INTO message_attachments (message_id, attachment_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type LinkMessageAttachmentParams struct {
	MessageID    uuid.UUID `json:"message_id"`
	AttachmentID uuid.UUID `json:"attachment_id"`
}

func (q *Queries) LinkMessageAttachment(ctx context.Context, arg LinkMessageAttachmentParams) error {
	_, err := q.db.Exec(ctx, linkMessageAttachment, arg.MessageID, arg.AttachmentID)
	return err
}

const listArtifactVersions = `-- name: ListArtifactVersions :many
SELECT id, artifact_id, version, created_by_message_id, created_at FROM artifact_versions WHERE artifact_id = $1 ORDER BY version
`

type ListArtifactVersionsRow struct {
	ID                 uuid.UUID     `json:"id"`
	ArtifactID         uuid.UUID     `json:"artifact_id"`
	Version            int32         `json:"version"`
	CreatedByMessageID uuid.NullUUID `json:"created_by_message_id"`
	CreatedAt          time.Time     `json:"created_at"`
}

func (q *Queries) ListArtifactVersions(ctx context.Context, artifactID uuid.UUID) ([]ListArtifactVersionsRow, error) {
	rows, err := q.db.Query(ctx, listArtifactVersions, artifactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtifactVersionsRow{}
	for rows.Next() {
		var i ListArtifactVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactID,
			&i.Version,
			&i.CreatedByMessageID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactsForConversation = `-- name: ListArtifactsForConversation :many
SELECT id, conversation_id, kind, title, language, current_version, created_at, updated_at FROM artifacts WHERE conversation_id = $1 ORDER BY created_at
`

func (q *Queries) ListArtifactsForConversation(ctx context.Context, conversationID uuid.UUID) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsForConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Kind,
			&i.Title,
			&i.Language,
			&i.CurrentVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsForMessage = `-- name: ListAttachmentsForMessage :many
SELECT a.id, a.user_id, a.blob_key, a.mime, a.bytes, a.sha256, a.filename, a.width, a.height, a.created_at FROM attachments a JOIN message_attachments ma ON ma.attachment_id = a.id WHERE ma.message_id = $1
`

func (q *Queries) ListAttachmentsForMessage(ctx context.Context, messageID uuid.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsForMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BlobKey,
			&i.Mime,
			&i.Bytes,
			&i.Sha256,
			&i.Filename,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsForProject = `-- name: ListConversationsForProject :many
SELECT id, project_id, user_id, title, mode, agent_id, model_selector, settings, compaction_head_message_seq, created_at, updated_at, archived_at FROM conversations WHERE project_id = $1 AND archived_at IS NULL
ORDER BY updated_at DESC LIMIT $2 OFFSET $3
`

type ListConversationsForProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListConversationsForProject(ctx context.Context, arg ListConversationsForProjectParams) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversationsForProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Title,
			&i.Mode,
			&i.AgentID,
			&i.ModelSelector,
			&i.Settings,
			&i.CompactionHeadMessageSeq,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, seq, role, parts, endpoint_id, model, usage, finish_reason, parent_id, created_at FROM messages WHERE conversation_id = $1 ORDER BY seq
`

func (q *Queries) ListMessages(ctx context.Context, conversationID uuid.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Seq,
			&i.Role,
			&i.Parts,
			&i.EndpointID,
			&i.Model,
			&i.Usage,
			&i.FinishReason,
			&i.ParentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesAfterSeq = `-- name: ListMessagesAfterSeq :many
SELECT id, conversation_id, seq, role, parts, endpoint_id, model, usage, finish_reason, parent_id, created_at FROM messages WHERE conversation_id = $1 AND seq > $2 ORDER BY seq
`

type ListMessagesAfterSeqParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	Seq            int64     `json:"seq"`
}

func (q *Queries) ListMessagesAfterSeq(ctx context.Context, arg ListMessagesAfterSeqParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesAfterSeq, arg.ConversationID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Seq,
			&i.Role,
			&i.Parts,
			&i.EndpointID,
			&i.Model,
			&i.Usage,
			&i.FinishReason,
			&i.ParentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesFromSeq = `-- name: ListMessagesFromSeq :many
SELECT id, conversation_id, seq, role, parts, endpoint_id, model, usage, finish_reason, parent_id, created_at FROM messages WHERE conversation_id = $1 AND seq >= $2 ORDER BY seq
`

type ListMessagesFromSeqParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	Seq            int64     `json:"seq"`
}

func (q *Queries) ListMessagesFromSeq(ctx context.Context, arg ListMessagesFromSeqParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesFromSeq, arg.ConversationID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Seq,
			&i.Role,
			&i.Parts,
			&i.EndpointID,
			&i.Model,
			&i.Usage,
			&i.FinishReason,
			&i.ParentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForUser = `-- name: ListProjectsForUser :many
SELECT p.id, p.owner_id, p.name, p.kind, p.settings, p.repo_url, p.default_branch, p.github_installation_id, p.created_at, p.updated_at, p.archived_at FROM projects p
LEFT JOIN project_members m ON m.project_id = p.id AND m.user_id = $1
WHERE p.archived_at IS NULL AND (p.owner_id = $1 OR m.user_id IS NOT NULL)
ORDER BY p.updated_at DESC
`

func (q *Queries) ListProjectsForUser(ctx context.Context, userID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Kind,
			&i.Settings,
			&i.RepoUrl,
			&i.DefaultBranch,
			&i.GithubInstallationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentConversationsForUser = `-- name: ListRecentConversationsForUser :many
SELECT id, project_id, user_id, title, mode, agent_id, model_selector, settings, compaction_head_message_seq, created_at, updated_at, archived_at FROM conversations WHERE user_id = $1 AND archived_at IS NULL
ORDER BY updated_at DESC LIMIT $2
`

type ListRecentConversationsForUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListRecentConversationsForUser(ctx context.Context, arg ListRecentConversationsForUserParams) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listRecentConversationsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Title,
			&i.Mode,
			&i.AgentID,
			&i.ModelSelector,
			&i.Settings,
			&i.CompactionHeadMessageSeq,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextMessageSeq = `-- name: NextMessageSeq :one
SELECT COALESCE(MAX(seq), 0) + 1 FROM messages WHERE conversation_id = $1
`

func (q *Queries) NextMessageSeq(ctx context.Context, conversationID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextMessageSeq, conversationID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const setCompactionHead = `-- name: SetCompactionHead :exec
UPDATE conversations SET compaction_head_message_seq = $2 WHERE id = $1
`

type SetCompactionHeadParams struct {
	ID                       uuid.UUID `json:"id"`
	CompactionHeadMessageSeq *int64    `json:"compaction_head_message_seq"`
}

func (q *Queries) SetCompactionHead(ctx context.Context, arg SetCompactionHeadParams) error {
	_, err := q.db.Exec(ctx, setCompactionHead, arg.ID, arg.CompactionHeadMessageSeq)
	return err
}

const touchConversation = `-- name: TouchConversation :exec
UPDATE conversations SET updated_at = now() WHERE id = $1
`

func (q *Queries) TouchConversation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchConversation, id)
	return err
}

const updateConversationSelector = `-- name: UpdateConversationSelector :exec
UPDATE conversations SET model_selector = $2 WHERE id = $1
`

type UpdateConversationSelectorParams struct {
	ID            uuid.UUID `json:"id"`
	ModelSelector string    `json:"model_selector"`
}

func (q *Queries) UpdateConversationSelector(ctx context.Context, arg UpdateConversationSelectorParams) error {
	_, err := q.db.Exec(ctx, updateConversationSelector, arg.ID, arg.ModelSelector)
	return err
}

const updateConversationSettings = `-- name: UpdateConversationSettings :exec
UPDATE conversations SET settings = $2 WHERE id = $1
`

type UpdateConversationSettingsParams struct {
	ID       uuid.UUID       `json:"id"`
	Settings json.RawMessage `json:"settings"`
}

func (q *Queries) UpdateConversationSettings(ctx context.Context, arg UpdateConversationSettingsParams) error {
	_, err := q.db.Exec(ctx, updateConversationSettings, arg.ID, arg.Settings)
	return err
}

const updateConversationTitle = `-- name: UpdateConversationTitle :exec
UPDATE conversations SET title = $2 WHERE id = $1
`

type UpdateConversationTitleParams struct {
	ID    uuid.UUID `json:"id"`
	Title string    `json:"title"`
}

func (q *Queries) UpdateConversationTitle(ctx context.Context, arg UpdateConversationTitleParams) error {
	_, err := q.db.Exec(ctx, updateConversationTitle, arg.ID, arg.Title)
	return err
}

const updateMessageParts = `-- name: UpdateMessageParts :exec
UPDATE messages SET parts = $2, endpoint_id = $3, model = $4, usage = $5, finish_reason = $6 WHERE id = $1
`

type UpdateMessagePartsParams struct {
	ID           uuid.UUID       `json:"id"`
	Parts        json.RawMessage `json:"parts"`
	EndpointID   *string         `json:"endpoint_id"`
	Model        *string         `json:"model"`
	Usage        json.RawMessage `json:"usage"`
	FinishReason *string         `json:"finish_reason"`
}

func (q *Queries) UpdateMessageParts(ctx context.Context, arg UpdateMessagePartsParams) error {
	_, err := q.db.Exec(ctx, updateMessageParts,
		arg.ID,
		arg.Parts,
		arg.EndpointID,
		arg.Model,
		arg.Usage,
		arg.FinishReason,
	)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET name = $2, kind = $3, settings = $4 WHERE id = $1 RETURNING id, owner_id, name, kind, settings, repo_url, default_branch, github_installation_id, created_at, updated_at, archived_at
`

type UpdateProjectParams struct {
	ID       uuid.UUID       `json:"id"`
	Name     string          `json:"name"`
	Kind     string          `json:"kind"`
	Settings json.RawMessage `json:"settings"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.Settings,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Kind,
		&i.Settings,
		&i.RepoUrl,
		&i.DefaultBranch,
		&i.GithubInstallationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const userCanAccessProject = `-- name: UserCanAccessProject :one
SELECT EXISTS (
  SELECT 1 FROM projects p
  LEFT JOIN project_members m ON m.project_id = p.id AND m.user_id = $2
  WHERE p.id = $1 AND p.archived_at IS NULL AND (p.owner_id = $2 OR m.user_id IS NOT NULL)
)
`

type UserCanAccessProjectParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UserCanAccessProject(ctx context.Context, arg UserCanAccessProjectParams) (bool, error) {
	row := q.db.QueryRow(ctx, userCanAccessProject, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
